// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/rsps/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestRspsRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerRspsRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/rsps_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	helper.RegisterExpectedRoutes(expectations)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestRspsPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/rsps": nil,
		"/rsps/{id1}": {"id1"},
		"/rsps/{id1}/rsp": {"id1"},
		"/rsps/{id1}/rsp/{id2}": {"id1", "id2"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestRspsHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerRspsRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/rsps", true},
		{"DELETE", "/rsps/{id1}", true},
		{"DELETE", "/rsps/{id1}/rsp", true},
		{"DELETE", "/rsps/{id1}/rsp/{id2}", true},
		{"GET", "/rsps", true},
		{"GET", "/rsps/{id1}", true},
		{"GET", "/rsps/{id1}/rsp", true},
		{"GET", "/rsps/{id1}/rsp/{id2}", true},
		{"HEAD", "/rsps", true},
		{"HEAD", "/rsps/{id1}", true},
		{"HEAD", "/rsps/{id1}/rsp", true},
		{"HEAD", "/rsps/{id1}/rsp/{id2}", true},
		{"POST", "/rsps", true},
		{"POST", "/rsps/{id1}", true},
		{"POST", "/rsps/{id1}/rsp", true},
		{"POST", "/rsps/{id1}/rsp/{id2}", true},
		{"PUT", "/rsps", true},
		{"PUT", "/rsps/{id1}", true},
		{"PUT", "/rsps/{id1}/rsp", true},
		{"PUT", "/rsps/{id1}/rsp/{id2}", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerRspsRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /rsps", http.HandlerFunc(h.DELETEResponseSetList))
	mux.Handle("DELETE /rsps/{id1}", http.HandlerFunc(h.DELETEResponseSet))
	mux.Handle("DELETE /rsps/{id1}/rsp", http.HandlerFunc(h.DELETEResponseList))
	mux.Handle("DELETE /rsps/{id1}/rsp/{id2}", http.HandlerFunc(h.DELETEResponse))
	mux.Handle("GET /rsps", http.HandlerFunc(h.GETResponseSetList))
	mux.Handle("GET /rsps/{id1}", http.HandlerFunc(h.GETResponseSet))
	mux.Handle("GET /rsps/{id1}/rsp", http.HandlerFunc(h.GETResponseList))
	mux.Handle("GET /rsps/{id1}/rsp/{id2}", http.HandlerFunc(h.GETResponse))
	mux.Handle("HEAD /rsps", http.HandlerFunc(h.HEADResponseSetList))
	mux.Handle("HEAD /rsps/{id1}", http.HandlerFunc(h.HEADResponseSet))
	mux.Handle("HEAD /rsps/{id1}/rsp", http.HandlerFunc(h.HEADResponseList))
	mux.Handle("HEAD /rsps/{id1}/rsp/{id2}", http.HandlerFunc(h.HEADResponse))
	mux.Handle("POST /rsps", http.HandlerFunc(h.POSTResponseSetList))
	mux.Handle("POST /rsps/{id1}", http.HandlerFunc(h.POSTResponseSet))
	mux.Handle("POST /rsps/{id1}/rsp", http.HandlerFunc(h.POSTResponseList))
	mux.Handle("POST /rsps/{id1}/rsp/{id2}", http.HandlerFunc(h.POSTResponse))
	mux.Handle("PUT /rsps", http.HandlerFunc(h.PUTResponseSetList))
	mux.Handle("PUT /rsps/{id1}", http.HandlerFunc(h.PUTResponseSet))
	mux.Handle("PUT /rsps/{id1}/rsp", http.HandlerFunc(h.PUTResponseList))
	mux.Handle("PUT /rsps/{id1}/rsp/{id2}", http.HandlerFunc(h.PUTResponse))
}
