// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/Notify/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestNotifyRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerNotifyRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/ntfy_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	helper.RegisterExpectedRoutes(expectations)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestNotifyPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/ntfy": nil,
		"/ntfy/{id1}": {"id1"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestNotifyHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerNotifyRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/ntfy", true},
		{"DELETE", "/ntfy/{id1}", true},
		{"GET", "/ntfy", true},
		{"GET", "/ntfy/{id1}", true},
		{"HEAD", "/ntfy", true},
		{"HEAD", "/ntfy/{id1}", true},
		{"POST", "/ntfy", true},
		{"POST", "/ntfy/{id1}", true},
		{"PUT", "/ntfy", true},
		{"PUT", "/ntfy/{id1}", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerNotifyRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /ntfy", http.HandlerFunc(h.DELETENotificationList))
	mux.Handle("DELETE /ntfy/{id1}", http.HandlerFunc(h.DELETENotification))
	mux.Handle("GET /ntfy", http.HandlerFunc(h.GETNotificationList))
	mux.Handle("GET /ntfy/{id1}", http.HandlerFunc(h.GETNotification))
	mux.Handle("HEAD /ntfy", http.HandlerFunc(h.HEADNotificationList))
	mux.Handle("HEAD /ntfy/{id1}", http.HandlerFunc(h.HEADNotification))
	mux.Handle("POST /ntfy", http.HandlerFunc(h.POSTNotificationList))
	mux.Handle("POST /ntfy/{id1}", http.HandlerFunc(h.POSTNotification))
	mux.Handle("PUT /ntfy", http.HandlerFunc(h.PUTNotificationList))
	mux.Handle("PUT /ntfy/{id1}", http.HandlerFunc(h.PUTNotification))
}
