// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/Messaging/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestMessagingRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerMessagingRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/msg_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	helper.RegisterExpectedRoutes(expectations)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestMessagingPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/msg": nil,
		"/msg/{id1}": {"id1"},
		"/msg/{id1}/acttxt": {"id1"},
		"/msg/{id1}/txt": {"id1"},
		"/msg/{id1}/txt/{id2}": {"id1", "id2"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestMessagingHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerMessagingRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/msg", true},
		{"DELETE", "/msg/{id1}", true},
		{"DELETE", "/msg/{id1}/acttxt", true},
		{"DELETE", "/msg/{id1}/txt", true},
		{"DELETE", "/msg/{id1}/txt/{id2}", true},
		{"GET", "/msg", true},
		{"GET", "/msg/{id1}", true},
		{"GET", "/msg/{id1}/acttxt", true},
		{"GET", "/msg/{id1}/txt", true},
		{"GET", "/msg/{id1}/txt/{id2}", true},
		{"HEAD", "/msg", true},
		{"HEAD", "/msg/{id1}", true},
		{"HEAD", "/msg/{id1}/acttxt", true},
		{"HEAD", "/msg/{id1}/txt", true},
		{"HEAD", "/msg/{id1}/txt/{id2}", true},
		{"POST", "/msg", true},
		{"POST", "/msg/{id1}", true},
		{"POST", "/msg/{id1}/acttxt", true},
		{"POST", "/msg/{id1}/txt", true},
		{"POST", "/msg/{id1}/txt/{id2}", true},
		{"PUT", "/msg", true},
		{"PUT", "/msg/{id1}", true},
		{"PUT", "/msg/{id1}/acttxt", true},
		{"PUT", "/msg/{id1}/txt", true},
		{"PUT", "/msg/{id1}/txt/{id2}", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerMessagingRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /msg", http.HandlerFunc(h.DELETEMessagingProgramList))
	mux.Handle("DELETE /msg/{id1}", http.HandlerFunc(h.DELETEMessagingProgram))
	mux.Handle("DELETE /msg/{id1}/acttxt", http.HandlerFunc(h.DELETEActiveTextMessageList))
	mux.Handle("DELETE /msg/{id1}/txt", http.HandlerFunc(h.DELETETextMessageList))
	mux.Handle("DELETE /msg/{id1}/txt/{id2}", http.HandlerFunc(h.DELETETextMessage))
	mux.Handle("GET /msg", http.HandlerFunc(h.GETMessagingProgramList))
	mux.Handle("GET /msg/{id1}", http.HandlerFunc(h.GETMessagingProgram))
	mux.Handle("GET /msg/{id1}/acttxt", http.HandlerFunc(h.GETActiveTextMessageList))
	mux.Handle("GET /msg/{id1}/txt", http.HandlerFunc(h.GETTextMessageList))
	mux.Handle("GET /msg/{id1}/txt/{id2}", http.HandlerFunc(h.GETTextMessage))
	mux.Handle("HEAD /msg", http.HandlerFunc(h.HEADMessagingProgramList))
	mux.Handle("HEAD /msg/{id1}", http.HandlerFunc(h.HEADMessagingProgram))
	mux.Handle("HEAD /msg/{id1}/acttxt", http.HandlerFunc(h.HEADActiveTextMessageList))
	mux.Handle("HEAD /msg/{id1}/txt", http.HandlerFunc(h.HEADTextMessageList))
	mux.Handle("HEAD /msg/{id1}/txt/{id2}", http.HandlerFunc(h.HEADTextMessage))
	mux.Handle("POST /msg", http.HandlerFunc(h.POSTMessagingProgramList))
	mux.Handle("POST /msg/{id1}", http.HandlerFunc(h.POSTMessagingProgram))
	mux.Handle("POST /msg/{id1}/acttxt", http.HandlerFunc(h.POSTActiveTextMessageList))
	mux.Handle("POST /msg/{id1}/txt", http.HandlerFunc(h.POSTTextMessageList))
	mux.Handle("POST /msg/{id1}/txt/{id2}", http.HandlerFunc(h.POSTTextMessage))
	mux.Handle("PUT /msg", http.HandlerFunc(h.PUTMessagingProgramList))
	mux.Handle("PUT /msg/{id1}", http.HandlerFunc(h.PUTMessagingProgram))
	mux.Handle("PUT /msg/{id1}/acttxt", http.HandlerFunc(h.PUTActiveTextMessageList))
	mux.Handle("PUT /msg/{id1}/txt", http.HandlerFunc(h.PUTTextMessageList))
	mux.Handle("PUT /msg/{id1}/txt/{id2}", http.HandlerFunc(h.PUTTextMessage))
}
