// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/TariffProfile/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestTariffprofileRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerTariffprofileRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/tp_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	helper.RegisterExpectedRoutes(expectations)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestTariffprofilePathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/tp": nil,
		"/tp/{id1}": {"id1"},
		"/tp/{id1}/rc": {"id1"},
		"/tp/{id1}/rc/{id2}": {"id1", "id2"},
		"/tp/{id1}/rc/{id2}/acttti": {"id1", "id2"},
		"/tp/{id1}/rc/{id2}/tti": {"id1", "id2"},
		"/tp/{id1}/rc/{id2}/tti/{id3}": {"id1", "id2", "id3"},
		"/tp/{id1}/rc/{id2}/tti/{id3}/cti": {"id1", "id2", "id3"},
		"/tp/{id1}/rc/{id2}/tti/{id3}/cti/{id4}": {"id1", "id2", "id3", "id4"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestTariffprofileHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerTariffprofileRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/tp", true},
		{"DELETE", "/tp/{id1}", true},
		{"DELETE", "/tp/{id1}/rc", true},
		{"DELETE", "/tp/{id1}/rc/{id2}", true},
		{"DELETE", "/tp/{id1}/rc/{id2}/acttti", true},
		{"DELETE", "/tp/{id1}/rc/{id2}/tti", true},
		{"DELETE", "/tp/{id1}/rc/{id2}/tti/{id3}", true},
		{"DELETE", "/tp/{id1}/rc/{id2}/tti/{id3}/cti", true},
		{"DELETE", "/tp/{id1}/rc/{id2}/tti/{id3}/cti/{id4}", true},
		{"GET", "/tp", true},
		{"GET", "/tp/{id1}", true},
		{"GET", "/tp/{id1}/rc", true},
		{"GET", "/tp/{id1}/rc/{id2}", true},
		{"GET", "/tp/{id1}/rc/{id2}/acttti", true},
		{"GET", "/tp/{id1}/rc/{id2}/tti", true},
		{"GET", "/tp/{id1}/rc/{id2}/tti/{id3}", true},
		{"GET", "/tp/{id1}/rc/{id2}/tti/{id3}/cti", true},
		{"GET", "/tp/{id1}/rc/{id2}/tti/{id3}/cti/{id4}", true},
		{"HEAD", "/tp", true},
		{"HEAD", "/tp/{id1}", true},
		{"HEAD", "/tp/{id1}/rc", true},
		{"HEAD", "/tp/{id1}/rc/{id2}", true},
		{"HEAD", "/tp/{id1}/rc/{id2}/acttti", true},
		{"HEAD", "/tp/{id1}/rc/{id2}/tti", true},
		{"HEAD", "/tp/{id1}/rc/{id2}/tti/{id3}", true},
		{"HEAD", "/tp/{id1}/rc/{id2}/tti/{id3}/cti", true},
		{"HEAD", "/tp/{id1}/rc/{id2}/tti/{id3}/cti/{id4}", true},
		{"POST", "/tp", true},
		{"POST", "/tp/{id1}", true},
		{"POST", "/tp/{id1}/rc", true},
		{"POST", "/tp/{id1}/rc/{id2}", true},
		{"POST", "/tp/{id1}/rc/{id2}/acttti", true},
		{"POST", "/tp/{id1}/rc/{id2}/tti", true},
		{"POST", "/tp/{id1}/rc/{id2}/tti/{id3}", true},
		{"POST", "/tp/{id1}/rc/{id2}/tti/{id3}/cti", true},
		{"POST", "/tp/{id1}/rc/{id2}/tti/{id3}/cti/{id4}", true},
		{"PUT", "/tp", true},
		{"PUT", "/tp/{id1}", true},
		{"PUT", "/tp/{id1}/rc", true},
		{"PUT", "/tp/{id1}/rc/{id2}", true},
		{"PUT", "/tp/{id1}/rc/{id2}/acttti", true},
		{"PUT", "/tp/{id1}/rc/{id2}/tti", true},
		{"PUT", "/tp/{id1}/rc/{id2}/tti/{id3}", true},
		{"PUT", "/tp/{id1}/rc/{id2}/tti/{id3}/cti", true},
		{"PUT", "/tp/{id1}/rc/{id2}/tti/{id3}/cti/{id4}", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerTariffprofileRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /tp", http.HandlerFunc(h.DELETETariffProfileList))
	mux.Handle("DELETE /tp/{id1}", http.HandlerFunc(h.DELETETariffProfile))
	mux.Handle("DELETE /tp/{id1}/rc", http.HandlerFunc(h.DELETERcList))
	mux.Handle("DELETE /tp/{id1}/rc/{id2}", http.HandlerFunc(h.DELETERc))
	mux.Handle("DELETE /tp/{id1}/rc/{id2}/acttti", http.HandlerFunc(h.DELETEActiveTimeTariffIntervalList))
	mux.Handle("DELETE /tp/{id1}/rc/{id2}/tti", http.HandlerFunc(h.DELETETimeTariffIntervalList))
	mux.Handle("DELETE /tp/{id1}/rc/{id2}/tti/{id3}", http.HandlerFunc(h.DELETETimeTariffInterval))
	mux.Handle("DELETE /tp/{id1}/rc/{id2}/tti/{id3}/cti", http.HandlerFunc(h.DELETEConsumptionTariffIntervalList))
	mux.Handle("DELETE /tp/{id1}/rc/{id2}/tti/{id3}/cti/{id4}", http.HandlerFunc(h.DELETEConsumptionTariffInterval))
	mux.Handle("GET /tp", http.HandlerFunc(h.GETTariffProfileList))
	mux.Handle("GET /tp/{id1}", http.HandlerFunc(h.GETTariffProfile))
	mux.Handle("GET /tp/{id1}/rc", http.HandlerFunc(h.GETRcList))
	mux.Handle("GET /tp/{id1}/rc/{id2}", http.HandlerFunc(h.GETRc))
	mux.Handle("GET /tp/{id1}/rc/{id2}/acttti", http.HandlerFunc(h.GETActiveTimeTariffIntervalList))
	mux.Handle("GET /tp/{id1}/rc/{id2}/tti", http.HandlerFunc(h.GETTimeTariffIntervalList))
	mux.Handle("GET /tp/{id1}/rc/{id2}/tti/{id3}", http.HandlerFunc(h.GETTimeTariffInterval))
	mux.Handle("GET /tp/{id1}/rc/{id2}/tti/{id3}/cti", http.HandlerFunc(h.GETConsumptionTariffIntervalList))
	mux.Handle("GET /tp/{id1}/rc/{id2}/tti/{id3}/cti/{id4}", http.HandlerFunc(h.GETConsumptionTariffInterval))
	mux.Handle("HEAD /tp", http.HandlerFunc(h.HEADTariffProfileList))
	mux.Handle("HEAD /tp/{id1}", http.HandlerFunc(h.HEADTariffProfile))
	mux.Handle("HEAD /tp/{id1}/rc", http.HandlerFunc(h.HEADRcList))
	mux.Handle("HEAD /tp/{id1}/rc/{id2}", http.HandlerFunc(h.HEADRc))
	mux.Handle("HEAD /tp/{id1}/rc/{id2}/acttti", http.HandlerFunc(h.HEADActiveTimeTariffIntervalList))
	mux.Handle("HEAD /tp/{id1}/rc/{id2}/tti", http.HandlerFunc(h.HEADTimeTariffIntervalList))
	mux.Handle("HEAD /tp/{id1}/rc/{id2}/tti/{id3}", http.HandlerFunc(h.HEADTimeTariffInterval))
	mux.Handle("HEAD /tp/{id1}/rc/{id2}/tti/{id3}/cti", http.HandlerFunc(h.HEADConsumptionTariffIntervalList))
	mux.Handle("HEAD /tp/{id1}/rc/{id2}/tti/{id3}/cti/{id4}", http.HandlerFunc(h.HEADConsumptionTariffInterval))
	mux.Handle("POST /tp", http.HandlerFunc(h.POSTTariffProfileList))
	mux.Handle("POST /tp/{id1}", http.HandlerFunc(h.POSTTariffProfile))
	mux.Handle("POST /tp/{id1}/rc", http.HandlerFunc(h.POSTRcList))
	mux.Handle("POST /tp/{id1}/rc/{id2}", http.HandlerFunc(h.POSTRc))
	mux.Handle("POST /tp/{id1}/rc/{id2}/acttti", http.HandlerFunc(h.POSTActiveTimeTariffIntervalList))
	mux.Handle("POST /tp/{id1}/rc/{id2}/tti", http.HandlerFunc(h.POSTTimeTariffIntervalList))
	mux.Handle("POST /tp/{id1}/rc/{id2}/tti/{id3}", http.HandlerFunc(h.POSTTimeTariffInterval))
	mux.Handle("POST /tp/{id1}/rc/{id2}/tti/{id3}/cti", http.HandlerFunc(h.POSTConsumptionTariffIntervalList))
	mux.Handle("POST /tp/{id1}/rc/{id2}/tti/{id3}/cti/{id4}", http.HandlerFunc(h.POSTConsumptionTariffInterval))
	mux.Handle("PUT /tp", http.HandlerFunc(h.PUTTariffProfileList))
	mux.Handle("PUT /tp/{id1}", http.HandlerFunc(h.PUTTariffProfile))
	mux.Handle("PUT /tp/{id1}/rc", http.HandlerFunc(h.PUTRcList))
	mux.Handle("PUT /tp/{id1}/rc/{id2}", http.HandlerFunc(h.PUTRc))
	mux.Handle("PUT /tp/{id1}/rc/{id2}/acttti", http.HandlerFunc(h.PUTActiveTimeTariffIntervalList))
	mux.Handle("PUT /tp/{id1}/rc/{id2}/tti", http.HandlerFunc(h.PUTTimeTariffIntervalList))
	mux.Handle("PUT /tp/{id1}/rc/{id2}/tti/{id3}", http.HandlerFunc(h.PUTTimeTariffInterval))
	mux.Handle("PUT /tp/{id1}/rc/{id2}/tti/{id3}/cti", http.HandlerFunc(h.PUTConsumptionTariffIntervalList))
	mux.Handle("PUT /tp/{id1}/rc/{id2}/tti/{id3}/cti/{id4}", http.HandlerFunc(h.PUTConsumptionTariffInterval))
}
