// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/PPY/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestPpyRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerPpyRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/ppy_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestPpyPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/ppy": nil,
		"/ppy/{id1}": {"id1"},
		"/ppy/{id1}/ab": {"id1"},
		"/ppy/{id1}/actsi": {"id1"},
		"/ppy/{id1}/cr": {"id1"},
		"/ppy/{id1}/cr/{id2}": {"id1", "id2"},
		"/ppy/{id1}/os": {"id1"},
		"/ppy/{id1}/si": {"id1"},
		"/ppy/{id1}/si/{id2}": {"id1", "id2"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestPpyHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerPpyRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/ppy", true},
		{"DELETE", "/ppy/{id1}", true},
		{"DELETE", "/ppy/{id1}/ab", true},
		{"DELETE", "/ppy/{id1}/actsi", true},
		{"DELETE", "/ppy/{id1}/cr", true},
		{"DELETE", "/ppy/{id1}/cr/{id2}", true},
		{"DELETE", "/ppy/{id1}/os", true},
		{"DELETE", "/ppy/{id1}/si", true},
		{"DELETE", "/ppy/{id1}/si/{id2}", true},
		{"GET", "/ppy", true},
		{"GET", "/ppy/{id1}", true},
		{"GET", "/ppy/{id1}/ab", true},
		{"GET", "/ppy/{id1}/actsi", true},
		{"GET", "/ppy/{id1}/cr", true},
		{"GET", "/ppy/{id1}/cr/{id2}", true},
		{"GET", "/ppy/{id1}/os", true},
		{"GET", "/ppy/{id1}/si", true},
		{"GET", "/ppy/{id1}/si/{id2}", true},
		{"HEAD", "/ppy", true},
		{"HEAD", "/ppy/{id1}", true},
		{"HEAD", "/ppy/{id1}/ab", true},
		{"HEAD", "/ppy/{id1}/actsi", true},
		{"HEAD", "/ppy/{id1}/cr", true},
		{"HEAD", "/ppy/{id1}/cr/{id2}", true},
		{"HEAD", "/ppy/{id1}/os", true},
		{"HEAD", "/ppy/{id1}/si", true},
		{"HEAD", "/ppy/{id1}/si/{id2}", true},
		{"POST", "/ppy", true},
		{"POST", "/ppy/{id1}", true},
		{"POST", "/ppy/{id1}/ab", true},
		{"POST", "/ppy/{id1}/actsi", true},
		{"POST", "/ppy/{id1}/cr", true},
		{"POST", "/ppy/{id1}/cr/{id2}", true},
		{"POST", "/ppy/{id1}/os", true},
		{"POST", "/ppy/{id1}/si", true},
		{"POST", "/ppy/{id1}/si/{id2}", true},
		{"PUT", "/ppy", true},
		{"PUT", "/ppy/{id1}", true},
		{"PUT", "/ppy/{id1}/ab", true},
		{"PUT", "/ppy/{id1}/actsi", true},
		{"PUT", "/ppy/{id1}/cr", true},
		{"PUT", "/ppy/{id1}/cr/{id2}", true},
		{"PUT", "/ppy/{id1}/os", true},
		{"PUT", "/ppy/{id1}/si", true},
		{"PUT", "/ppy/{id1}/si/{id2}", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerPpyRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /ppy", http.HandlerFunc(h.DELETEPrepaymentList))
	mux.Handle("DELETE /ppy/{id1}", http.HandlerFunc(h.DELETEPrepayment))
	mux.Handle("DELETE /ppy/{id1}/ab", http.HandlerFunc(h.DELETEAccountBalance))
	mux.Handle("DELETE /ppy/{id1}/actsi", http.HandlerFunc(h.DELETEActiveSupplyInterruptionOverrideList))
	mux.Handle("DELETE /ppy/{id1}/cr", http.HandlerFunc(h.DELETECreditRegisterList))
	mux.Handle("DELETE /ppy/{id1}/cr/{id2}", http.HandlerFunc(h.DELETECreditRegister))
	mux.Handle("DELETE /ppy/{id1}/os", http.HandlerFunc(h.DELETEPrepayOperationStatus))
	mux.Handle("DELETE /ppy/{id1}/si", http.HandlerFunc(h.DELETESupplyInterruptionOverrideList))
	mux.Handle("DELETE /ppy/{id1}/si/{id2}", http.HandlerFunc(h.DELETESupplyInterruptionOverride))
	mux.Handle("GET /ppy", http.HandlerFunc(h.GETPrepaymentList))
	mux.Handle("GET /ppy/{id1}", http.HandlerFunc(h.GETPrepayment))
	mux.Handle("GET /ppy/{id1}/ab", http.HandlerFunc(h.GETAccountBalance))
	mux.Handle("GET /ppy/{id1}/actsi", http.HandlerFunc(h.GETActiveSupplyInterruptionOverrideList))
	mux.Handle("GET /ppy/{id1}/cr", http.HandlerFunc(h.GETCreditRegisterList))
	mux.Handle("GET /ppy/{id1}/cr/{id2}", http.HandlerFunc(h.GETCreditRegister))
	mux.Handle("GET /ppy/{id1}/os", http.HandlerFunc(h.GETPrepayOperationStatus))
	mux.Handle("GET /ppy/{id1}/si", http.HandlerFunc(h.GETSupplyInterruptionOverrideList))
	mux.Handle("GET /ppy/{id1}/si/{id2}", http.HandlerFunc(h.GETSupplyInterruptionOverride))
	mux.Handle("HEAD /ppy", http.HandlerFunc(h.HEADPrepaymentList))
	mux.Handle("HEAD /ppy/{id1}", http.HandlerFunc(h.HEADPrepayment))
	mux.Handle("HEAD /ppy/{id1}/ab", http.HandlerFunc(h.HEADAccountBalance))
	mux.Handle("HEAD /ppy/{id1}/actsi", http.HandlerFunc(h.HEADActiveSupplyInterruptionOverrideList))
	mux.Handle("HEAD /ppy/{id1}/cr", http.HandlerFunc(h.HEADCreditRegisterList))
	mux.Handle("HEAD /ppy/{id1}/cr/{id2}", http.HandlerFunc(h.HEADCreditRegister))
	mux.Handle("HEAD /ppy/{id1}/os", http.HandlerFunc(h.HEADPrepayOperationStatus))
	mux.Handle("HEAD /ppy/{id1}/si", http.HandlerFunc(h.HEADSupplyInterruptionOverrideList))
	mux.Handle("HEAD /ppy/{id1}/si/{id2}", http.HandlerFunc(h.HEADSupplyInterruptionOverride))
	mux.Handle("POST /ppy", http.HandlerFunc(h.POSTPrepaymentList))
	mux.Handle("POST /ppy/{id1}", http.HandlerFunc(h.POSTPrepayment))
	mux.Handle("POST /ppy/{id1}/ab", http.HandlerFunc(h.POSTAccountBalance))
	mux.Handle("POST /ppy/{id1}/actsi", http.HandlerFunc(h.POSTActiveSupplyInterruptionOverrideList))
	mux.Handle("POST /ppy/{id1}/cr", http.HandlerFunc(h.POSTCreditRegisterList))
	mux.Handle("POST /ppy/{id1}/cr/{id2}", http.HandlerFunc(h.POSTCreditRegister))
	mux.Handle("POST /ppy/{id1}/os", http.HandlerFunc(h.POSTPrepayOperationStatus))
	mux.Handle("POST /ppy/{id1}/si", http.HandlerFunc(h.POSTSupplyInterruptionOverrideList))
	mux.Handle("POST /ppy/{id1}/si/{id2}", http.HandlerFunc(h.POSTSupplyInterruptionOverride))
	mux.Handle("PUT /ppy", http.HandlerFunc(h.PUTPrepaymentList))
	mux.Handle("PUT /ppy/{id1}", http.HandlerFunc(h.PUTPrepayment))
	mux.Handle("PUT /ppy/{id1}/ab", http.HandlerFunc(h.PUTAccountBalance))
	mux.Handle("PUT /ppy/{id1}/actsi", http.HandlerFunc(h.PUTActiveSupplyInterruptionOverrideList))
	mux.Handle("PUT /ppy/{id1}/cr", http.HandlerFunc(h.PUTCreditRegisterList))
	mux.Handle("PUT /ppy/{id1}/cr/{id2}", http.HandlerFunc(h.PUTCreditRegister))
	mux.Handle("PUT /ppy/{id1}/os", http.HandlerFunc(h.PUTPrepayOperationStatus))
	mux.Handle("PUT /ppy/{id1}/si", http.HandlerFunc(h.PUTSupplyInterruptionOverrideList))
	mux.Handle("PUT /ppy/{id1}/si/{id2}", http.HandlerFunc(h.PUTSupplyInterruptionOverride))
}
