// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/BRS/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestBrsRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerBrsRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/brs_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	helper.RegisterExpectedRoutes(expectations)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestBrsPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/brs": nil,
		"/brs/{id1}": {"id1"},
		"/brs/{id1}/br": {"id1"},
		"/brs/{id1}/br/{id2}": {"id1", "id2"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestBrsHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerBrsRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/brs", true},
		{"DELETE", "/brs/{id1}", true},
		{"DELETE", "/brs/{id1}/br", true},
		{"DELETE", "/brs/{id1}/br/{id2}", true},
		{"GET", "/brs", true},
		{"GET", "/brs/{id1}", true},
		{"GET", "/brs/{id1}/br", true},
		{"GET", "/brs/{id1}/br/{id2}", true},
		{"HEAD", "/brs", true},
		{"HEAD", "/brs/{id1}", true},
		{"HEAD", "/brs/{id1}/br", true},
		{"HEAD", "/brs/{id1}/br/{id2}", true},
		{"POST", "/brs", true},
		{"POST", "/brs/{id1}", true},
		{"POST", "/brs/{id1}/br", true},
		{"POST", "/brs/{id1}/br/{id2}", true},
		{"PUT", "/brs", true},
		{"PUT", "/brs/{id1}", true},
		{"PUT", "/brs/{id1}/br", true},
		{"PUT", "/brs/{id1}/br/{id2}", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerBrsRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /brs", http.HandlerFunc(h.DELETEBillingReadingSetList))
	mux.Handle("DELETE /brs/{id1}", http.HandlerFunc(h.DELETEBillingReadingSet))
	mux.Handle("DELETE /brs/{id1}/br", http.HandlerFunc(h.DELETEBillingReadingList))
	mux.Handle("DELETE /brs/{id1}/br/{id2}", http.HandlerFunc(h.DELETEBillingReading))
	mux.Handle("GET /brs", http.HandlerFunc(h.GETBillingReadingSetList))
	mux.Handle("GET /brs/{id1}", http.HandlerFunc(h.GETBillingReadingSet))
	mux.Handle("GET /brs/{id1}/br", http.HandlerFunc(h.GETBillingReadingList))
	mux.Handle("GET /brs/{id1}/br/{id2}", http.HandlerFunc(h.GETBillingReading))
	mux.Handle("HEAD /brs", http.HandlerFunc(h.HEADBillingReadingSetList))
	mux.Handle("HEAD /brs/{id1}", http.HandlerFunc(h.HEADBillingReadingSet))
	mux.Handle("HEAD /brs/{id1}/br", http.HandlerFunc(h.HEADBillingReadingList))
	mux.Handle("HEAD /brs/{id1}/br/{id2}", http.HandlerFunc(h.HEADBillingReading))
	mux.Handle("POST /brs", http.HandlerFunc(h.POSTBillingReadingSetList))
	mux.Handle("POST /brs/{id1}", http.HandlerFunc(h.POSTBillingReadingSet))
	mux.Handle("POST /brs/{id1}/br", http.HandlerFunc(h.POSTBillingReadingList))
	mux.Handle("POST /brs/{id1}/br/{id2}", http.HandlerFunc(h.POSTBillingReading))
	mux.Handle("PUT /brs", http.HandlerFunc(h.PUTBillingReadingSetList))
	mux.Handle("PUT /brs/{id1}", http.HandlerFunc(h.PUTBillingReadingSet))
	mux.Handle("PUT /brs/{id1}/br", http.HandlerFunc(h.PUTBillingReadingList))
	mux.Handle("PUT /brs/{id1}/br/{id2}", http.HandlerFunc(h.PUTBillingReading))
}
