// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/DERP/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestDerpRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerDerpRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/derp_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestDerpPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/derp": nil,
		"/derp/{id1}": {"id1"},
		"/derp/{id1}/actderc": {"id1"},
		"/derp/{id1}/dc": {"id1"},
		"/derp/{id1}/dc/{id2}": {"id1", "id2"},
		"/derp/{id1}/dderc": {"id1"},
		"/derp/{id1}/derc": {"id1"},
		"/derp/{id1}/derc/{id2}": {"id1", "id2"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestDerpHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerDerpRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/derp", true},
		{"DELETE", "/derp/{id1}", true},
		{"DELETE", "/derp/{id1}/actderc", true},
		{"DELETE", "/derp/{id1}/dc", true},
		{"DELETE", "/derp/{id1}/dc/{id2}", true},
		{"DELETE", "/derp/{id1}/dderc", true},
		{"DELETE", "/derp/{id1}/derc", true},
		{"DELETE", "/derp/{id1}/derc/{id2}", true},
		{"GET", "/derp", true},
		{"GET", "/derp/{id1}", true},
		{"GET", "/derp/{id1}/actderc", true},
		{"GET", "/derp/{id1}/dc", true},
		{"GET", "/derp/{id1}/dc/{id2}", true},
		{"GET", "/derp/{id1}/dderc", true},
		{"GET", "/derp/{id1}/derc", true},
		{"GET", "/derp/{id1}/derc/{id2}", true},
		{"HEAD", "/derp", true},
		{"HEAD", "/derp/{id1}", true},
		{"HEAD", "/derp/{id1}/actderc", true},
		{"HEAD", "/derp/{id1}/dc", true},
		{"HEAD", "/derp/{id1}/dc/{id2}", true},
		{"HEAD", "/derp/{id1}/dderc", true},
		{"HEAD", "/derp/{id1}/derc", true},
		{"HEAD", "/derp/{id1}/derc/{id2}", true},
		{"POST", "/derp", true},
		{"POST", "/derp/{id1}", true},
		{"POST", "/derp/{id1}/actderc", true},
		{"POST", "/derp/{id1}/dc", true},
		{"POST", "/derp/{id1}/dc/{id2}", true},
		{"POST", "/derp/{id1}/dderc", true},
		{"POST", "/derp/{id1}/derc", true},
		{"POST", "/derp/{id1}/derc/{id2}", true},
		{"PUT", "/derp", true},
		{"PUT", "/derp/{id1}", true},
		{"PUT", "/derp/{id1}/actderc", true},
		{"PUT", "/derp/{id1}/dc", true},
		{"PUT", "/derp/{id1}/dc/{id2}", true},
		{"PUT", "/derp/{id1}/dderc", true},
		{"PUT", "/derp/{id1}/derc", true},
		{"PUT", "/derp/{id1}/derc/{id2}", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerDerpRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /derp", http.HandlerFunc(h.DELETEDERProgramList))
	mux.Handle("DELETE /derp/{id1}", http.HandlerFunc(h.DELETEDERProgram))
	mux.Handle("DELETE /derp/{id1}/actderc", http.HandlerFunc(h.DELETEActiveDERControlList))
	mux.Handle("DELETE /derp/{id1}/dc", http.HandlerFunc(h.DELETEDERCurveList))
	mux.Handle("DELETE /derp/{id1}/dc/{id2}", http.HandlerFunc(h.DELETEDERCurve))
	mux.Handle("DELETE /derp/{id1}/dderc", http.HandlerFunc(h.DELETEDefaultDERControlList))
	mux.Handle("DELETE /derp/{id1}/derc", http.HandlerFunc(h.DELETEDERControlList))
	mux.Handle("DELETE /derp/{id1}/derc/{id2}", http.HandlerFunc(h.DELETEDERControl))
	mux.Handle("GET /derp", http.HandlerFunc(h.GETDERProgramList))
	mux.Handle("GET /derp/{id1}", http.HandlerFunc(h.GETDERProgram))
	mux.Handle("GET /derp/{id1}/actderc", http.HandlerFunc(h.GETActiveDERControlList))
	mux.Handle("GET /derp/{id1}/dc", http.HandlerFunc(h.GETDERCurveList))
	mux.Handle("GET /derp/{id1}/dc/{id2}", http.HandlerFunc(h.GETDERCurve))
	mux.Handle("GET /derp/{id1}/dderc", http.HandlerFunc(h.GETDefaultDERControlList))
	mux.Handle("GET /derp/{id1}/derc", http.HandlerFunc(h.GETDERControlList))
	mux.Handle("GET /derp/{id1}/derc/{id2}", http.HandlerFunc(h.GETDERControl))
	mux.Handle("HEAD /derp", http.HandlerFunc(h.HEADDERProgramList))
	mux.Handle("HEAD /derp/{id1}", http.HandlerFunc(h.HEADDERProgram))
	mux.Handle("HEAD /derp/{id1}/actderc", http.HandlerFunc(h.HEADActiveDERControlList))
	mux.Handle("HEAD /derp/{id1}/dc", http.HandlerFunc(h.HEADDERCurveList))
	mux.Handle("HEAD /derp/{id1}/dc/{id2}", http.HandlerFunc(h.HEADDERCurve))
	mux.Handle("HEAD /derp/{id1}/dderc", http.HandlerFunc(h.HEADDefaultDERControlList))
	mux.Handle("HEAD /derp/{id1}/derc", http.HandlerFunc(h.HEADDERControlList))
	mux.Handle("HEAD /derp/{id1}/derc/{id2}", http.HandlerFunc(h.HEADDERControl))
	mux.Handle("POST /derp", http.HandlerFunc(h.POSTDERProgramList))
	mux.Handle("POST /derp/{id1}", http.HandlerFunc(h.POSTDERProgram))
	mux.Handle("POST /derp/{id1}/actderc", http.HandlerFunc(h.POSTActiveDERControlList))
	mux.Handle("POST /derp/{id1}/dc", http.HandlerFunc(h.POSTDERCurveList))
	mux.Handle("POST /derp/{id1}/dc/{id2}", http.HandlerFunc(h.POSTDERCurve))
	mux.Handle("POST /derp/{id1}/dderc", http.HandlerFunc(h.POSTDefaultDERControlList))
	mux.Handle("POST /derp/{id1}/derc", http.HandlerFunc(h.POSTDERControlList))
	mux.Handle("POST /derp/{id1}/derc/{id2}", http.HandlerFunc(h.POSTDERControl))
	mux.Handle("PUT /derp", http.HandlerFunc(h.PUTDERProgramList))
	mux.Handle("PUT /derp/{id1}", http.HandlerFunc(h.PUTDERProgram))
	mux.Handle("PUT /derp/{id1}/actderc", http.HandlerFunc(h.PUTActiveDERControlList))
	mux.Handle("PUT /derp/{id1}/dc", http.HandlerFunc(h.PUTDERCurveList))
	mux.Handle("PUT /derp/{id1}/dc/{id2}", http.HandlerFunc(h.PUTDERCurve))
	mux.Handle("PUT /derp/{id1}/dderc", http.HandlerFunc(h.PUTDefaultDERControlList))
	mux.Handle("PUT /derp/{id1}/derc", http.HandlerFunc(h.PUTDERControlList))
	mux.Handle("PUT /derp/{id1}/derc/{id2}", http.HandlerFunc(h.PUTDERControl))
}
