// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/FlowReservation/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestFlowreservationRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerFlowreservationRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/frq_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	helper.RegisterExpectedRoutes(expectations)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestFlowreservationPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/frp": nil,
		"/frp/{id1}": {"id1"},
		"/frq": nil,
		"/frq/{id1}": {"id1"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestFlowreservationHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerFlowreservationRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/frp", true},
		{"DELETE", "/frp/{id1}", true},
		{"DELETE", "/frq", true},
		{"DELETE", "/frq/{id1}", true},
		{"GET", "/frp", true},
		{"GET", "/frp/{id1}", true},
		{"GET", "/frq", true},
		{"GET", "/frq/{id1}", true},
		{"HEAD", "/frp", true},
		{"HEAD", "/frp/{id1}", true},
		{"HEAD", "/frq", true},
		{"HEAD", "/frq/{id1}", true},
		{"POST", "/frp", true},
		{"POST", "/frp/{id1}", true},
		{"POST", "/frq", true},
		{"POST", "/frq/{id1}", true},
		{"PUT", "/frp", true},
		{"PUT", "/frp/{id1}", true},
		{"PUT", "/frq", true},
		{"PUT", "/frq/{id1}", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerFlowreservationRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /frp", http.HandlerFunc(h.DELETEFlowReservationResponseList))
	mux.Handle("DELETE /frp/{id1}", http.HandlerFunc(h.DELETEFlowReservationResponse))
	mux.Handle("DELETE /frq", http.HandlerFunc(h.DELETEFlowReservationRequestList))
	mux.Handle("DELETE /frq/{id1}", http.HandlerFunc(h.DELETEFlowReservationRequest))
	mux.Handle("GET /frp", http.HandlerFunc(h.GETFlowReservationResponseList))
	mux.Handle("GET /frp/{id1}", http.HandlerFunc(h.GETFlowReservationResponse))
	mux.Handle("GET /frq", http.HandlerFunc(h.GETFlowReservationRequestList))
	mux.Handle("GET /frq/{id1}", http.HandlerFunc(h.GETFlowReservationRequest))
	mux.Handle("HEAD /frp", http.HandlerFunc(h.HEADFlowReservationResponseList))
	mux.Handle("HEAD /frp/{id1}", http.HandlerFunc(h.HEADFlowReservationResponse))
	mux.Handle("HEAD /frq", http.HandlerFunc(h.HEADFlowReservationRequestList))
	mux.Handle("HEAD /frq/{id1}", http.HandlerFunc(h.HEADFlowReservationRequest))
	mux.Handle("POST /frp", http.HandlerFunc(h.POSTFlowReservationResponseList))
	mux.Handle("POST /frp/{id1}", http.HandlerFunc(h.POSTFlowReservationResponse))
	mux.Handle("POST /frq", http.HandlerFunc(h.POSTFlowReservationRequestList))
	mux.Handle("POST /frq/{id1}", http.HandlerFunc(h.POSTFlowReservationRequest))
	mux.Handle("PUT /frp", http.HandlerFunc(h.PUTFlowReservationResponseList))
	mux.Handle("PUT /frp/{id1}", http.HandlerFunc(h.PUTFlowReservationResponse))
	mux.Handle("PUT /frq", http.HandlerFunc(h.PUTFlowReservationRequestList))
	mux.Handle("PUT /frq/{id1}", http.HandlerFunc(h.PUTFlowReservationRequest))
}
