// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/UPT/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestUptRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerUptRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/upt_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	helper.RegisterExpectedRoutes(expectations)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestUptPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/upt": nil,
		"/upt/{id1}": {"id1"},
		"/upt/{id1}/mr": {"id1"},
		"/upt/{id1}/mr/{id2}": {"id1", "id2"},
		"/upt/{id1}/mr/{id2}/rs": {"id1", "id2"},
		"/upt/{id1}/mr/{id2}/rs/{id3}": {"id1", "id2", "id3"},
		"/upt/{id1}/mr/{id2}/rs/{id3}/r": {"id1", "id2", "id3"},
		"/upt/{id1}/mr/{id2}/rs/{id3}/r/{id4}": {"id1", "id2", "id3", "id4"},
		"/upt/{id1}/mr/{id2}/rt": {"id1", "id2"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestUptHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerUptRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/upt", true},
		{"DELETE", "/upt/{id1}", true},
		{"DELETE", "/upt/{id1}/mr", true},
		{"DELETE", "/upt/{id1}/mr/{id2}", true},
		{"DELETE", "/upt/{id1}/mr/{id2}/rs", true},
		{"DELETE", "/upt/{id1}/mr/{id2}/rs/{id3}", true},
		{"DELETE", "/upt/{id1}/mr/{id2}/rs/{id3}/r", true},
		{"DELETE", "/upt/{id1}/mr/{id2}/rs/{id3}/r/{id4}", true},
		{"DELETE", "/upt/{id1}/mr/{id2}/rt", true},
		{"GET", "/upt", true},
		{"GET", "/upt/{id1}", true},
		{"GET", "/upt/{id1}/mr", true},
		{"GET", "/upt/{id1}/mr/{id2}", true},
		{"GET", "/upt/{id1}/mr/{id2}/rs", true},
		{"GET", "/upt/{id1}/mr/{id2}/rs/{id3}", true},
		{"GET", "/upt/{id1}/mr/{id2}/rs/{id3}/r", true},
		{"GET", "/upt/{id1}/mr/{id2}/rs/{id3}/r/{id4}", true},
		{"GET", "/upt/{id1}/mr/{id2}/rt", true},
		{"HEAD", "/upt", true},
		{"HEAD", "/upt/{id1}", true},
		{"HEAD", "/upt/{id1}/mr", true},
		{"HEAD", "/upt/{id1}/mr/{id2}", true},
		{"HEAD", "/upt/{id1}/mr/{id2}/rs", true},
		{"HEAD", "/upt/{id1}/mr/{id2}/rs/{id3}", true},
		{"HEAD", "/upt/{id1}/mr/{id2}/rs/{id3}/r", true},
		{"HEAD", "/upt/{id1}/mr/{id2}/rs/{id3}/r/{id4}", true},
		{"HEAD", "/upt/{id1}/mr/{id2}/rt", true},
		{"POST", "/upt", true},
		{"POST", "/upt/{id1}", true},
		{"POST", "/upt/{id1}/mr", true},
		{"POST", "/upt/{id1}/mr/{id2}", true},
		{"POST", "/upt/{id1}/mr/{id2}/rs", true},
		{"POST", "/upt/{id1}/mr/{id2}/rs/{id3}", true},
		{"POST", "/upt/{id1}/mr/{id2}/rs/{id3}/r", true},
		{"POST", "/upt/{id1}/mr/{id2}/rs/{id3}/r/{id4}", true},
		{"POST", "/upt/{id1}/mr/{id2}/rt", true},
		{"PUT", "/upt", true},
		{"PUT", "/upt/{id1}", true},
		{"PUT", "/upt/{id1}/mr", true},
		{"PUT", "/upt/{id1}/mr/{id2}", true},
		{"PUT", "/upt/{id1}/mr/{id2}/rs", true},
		{"PUT", "/upt/{id1}/mr/{id2}/rs/{id3}", true},
		{"PUT", "/upt/{id1}/mr/{id2}/rs/{id3}/r", true},
		{"PUT", "/upt/{id1}/mr/{id2}/rs/{id3}/r/{id4}", true},
		{"PUT", "/upt/{id1}/mr/{id2}/rt", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerUptRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /upt", http.HandlerFunc(h.DELETEUsagePointList))
	mux.Handle("DELETE /upt/{id1}", http.HandlerFunc(h.DELETEUsagePoint))
	mux.Handle("DELETE /upt/{id1}/mr", http.HandlerFunc(h.DELETEMeterReadingList))
	mux.Handle("DELETE /upt/{id1}/mr/{id2}", http.HandlerFunc(h.DELETEMeterReading))
	mux.Handle("DELETE /upt/{id1}/mr/{id2}/rs", http.HandlerFunc(h.DELETEReadingSetList))
	mux.Handle("DELETE /upt/{id1}/mr/{id2}/rs/{id3}", http.HandlerFunc(h.DELETEReadingSet))
	mux.Handle("DELETE /upt/{id1}/mr/{id2}/rs/{id3}/r", http.HandlerFunc(h.DELETEReadingList))
	mux.Handle("DELETE /upt/{id1}/mr/{id2}/rs/{id3}/r/{id4}", http.HandlerFunc(h.DELETEReading))
	mux.Handle("DELETE /upt/{id1}/mr/{id2}/rt", http.HandlerFunc(h.DELETEReadingType))
	mux.Handle("GET /upt", http.HandlerFunc(h.GETUsagePointList))
	mux.Handle("GET /upt/{id1}", http.HandlerFunc(h.GETUsagePoint))
	mux.Handle("GET /upt/{id1}/mr", http.HandlerFunc(h.GETMeterReadingList))
	mux.Handle("GET /upt/{id1}/mr/{id2}", http.HandlerFunc(h.GETMeterReading))
	mux.Handle("GET /upt/{id1}/mr/{id2}/rs", http.HandlerFunc(h.GETReadingSetList))
	mux.Handle("GET /upt/{id1}/mr/{id2}/rs/{id3}", http.HandlerFunc(h.GETReadingSet))
	mux.Handle("GET /upt/{id1}/mr/{id2}/rs/{id3}/r", http.HandlerFunc(h.GETReadingList))
	mux.Handle("GET /upt/{id1}/mr/{id2}/rs/{id3}/r/{id4}", http.HandlerFunc(h.GETReading))
	mux.Handle("GET /upt/{id1}/mr/{id2}/rt", http.HandlerFunc(h.GETReadingType))
	mux.Handle("HEAD /upt", http.HandlerFunc(h.HEADUsagePointList))
	mux.Handle("HEAD /upt/{id1}", http.HandlerFunc(h.HEADUsagePoint))
	mux.Handle("HEAD /upt/{id1}/mr", http.HandlerFunc(h.HEADMeterReadingList))
	mux.Handle("HEAD /upt/{id1}/mr/{id2}", http.HandlerFunc(h.HEADMeterReading))
	mux.Handle("HEAD /upt/{id1}/mr/{id2}/rs", http.HandlerFunc(h.HEADReadingSetList))
	mux.Handle("HEAD /upt/{id1}/mr/{id2}/rs/{id3}", http.HandlerFunc(h.HEADReadingSet))
	mux.Handle("HEAD /upt/{id1}/mr/{id2}/rs/{id3}/r", http.HandlerFunc(h.HEADReadingList))
	mux.Handle("HEAD /upt/{id1}/mr/{id2}/rs/{id3}/r/{id4}", http.HandlerFunc(h.HEADReading))
	mux.Handle("HEAD /upt/{id1}/mr/{id2}/rt", http.HandlerFunc(h.HEADReadingType))
	mux.Handle("POST /upt", http.HandlerFunc(h.POSTUsagePointList))
	mux.Handle("POST /upt/{id1}", http.HandlerFunc(h.POSTUsagePoint))
	mux.Handle("POST /upt/{id1}/mr", http.HandlerFunc(h.POSTMeterReadingList))
	mux.Handle("POST /upt/{id1}/mr/{id2}", http.HandlerFunc(h.POSTMeterReading))
	mux.Handle("POST /upt/{id1}/mr/{id2}/rs", http.HandlerFunc(h.POSTReadingSetList))
	mux.Handle("POST /upt/{id1}/mr/{id2}/rs/{id3}", http.HandlerFunc(h.POSTReadingSet))
	mux.Handle("POST /upt/{id1}/mr/{id2}/rs/{id3}/r", http.HandlerFunc(h.POSTReadingList))
	mux.Handle("POST /upt/{id1}/mr/{id2}/rs/{id3}/r/{id4}", http.HandlerFunc(h.POSTReading))
	mux.Handle("POST /upt/{id1}/mr/{id2}/rt", http.HandlerFunc(h.POSTReadingType))
	mux.Handle("PUT /upt", http.HandlerFunc(h.PUTUsagePointList))
	mux.Handle("PUT /upt/{id1}", http.HandlerFunc(h.PUTUsagePoint))
	mux.Handle("PUT /upt/{id1}/mr", http.HandlerFunc(h.PUTMeterReadingList))
	mux.Handle("PUT /upt/{id1}/mr/{id2}", http.HandlerFunc(h.PUTMeterReading))
	mux.Handle("PUT /upt/{id1}/mr/{id2}/rs", http.HandlerFunc(h.PUTReadingSetList))
	mux.Handle("PUT /upt/{id1}/mr/{id2}/rs/{id3}", http.HandlerFunc(h.PUTReadingSet))
	mux.Handle("PUT /upt/{id1}/mr/{id2}/rs/{id3}/r", http.HandlerFunc(h.PUTReadingList))
	mux.Handle("PUT /upt/{id1}/mr/{id2}/rs/{id3}/r/{id4}", http.HandlerFunc(h.PUTReading))
	mux.Handle("PUT /upt/{id1}/mr/{id2}/rt", http.HandlerFunc(h.PUTReadingType))
}
