// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/DER/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestDerRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerDerRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/der_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestDerPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/edev/{id1}/der": {"id1"},
		"/edev/{id1}/der/{id2}": {"id1", "id2"},
		"/edev/{id1}/der/{id2}/cdc": {"id1", "id2"},
		"/edev/{id1}/der/{id2}/cdp": {"id1", "id2"},
		"/edev/{id1}/der/{id2}/dera": {"id1", "id2"},
		"/edev/{id1}/der/{id2}/dercap": {"id1", "id2"},
		"/edev/{id1}/der/{id2}/dercom": {"id1", "id2"},
		"/edev/{id1}/der/{id2}/dercom/{id3}": {"id1", "id2", "id3"},
		"/edev/{id1}/der/{id2}/derg": {"id1", "id2"},
		"/edev/{id1}/der/{id2}/derp": {"id1", "id2"},
		"/edev/{id1}/der/{id2}/ders": {"id1", "id2"},
		"/edev/{id1}/der/{id2}/upt": {"id1", "id2"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestDerHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerDerRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/edev/{id1}/der", true},
		{"DELETE", "/edev/{id1}/der/{id2}", true},
		{"DELETE", "/edev/{id1}/der/{id2}/cdc", true},
		{"DELETE", "/edev/{id1}/der/{id2}/cdp", true},
		{"DELETE", "/edev/{id1}/der/{id2}/dera", true},
		{"DELETE", "/edev/{id1}/der/{id2}/dercap", true},
		{"DELETE", "/edev/{id1}/der/{id2}/dercom", true},
		{"DELETE", "/edev/{id1}/der/{id2}/dercom/{id3}", true},
		{"DELETE", "/edev/{id1}/der/{id2}/derg", true},
		{"DELETE", "/edev/{id1}/der/{id2}/derp", true},
		{"DELETE", "/edev/{id1}/der/{id2}/ders", true},
		{"DELETE", "/edev/{id1}/der/{id2}/upt", true},
		{"GET", "/edev/{id1}/der", true},
		{"GET", "/edev/{id1}/der/{id2}", true},
		{"GET", "/edev/{id1}/der/{id2}/cdc", true},
		{"GET", "/edev/{id1}/der/{id2}/cdp", true},
		{"GET", "/edev/{id1}/der/{id2}/dera", true},
		{"GET", "/edev/{id1}/der/{id2}/dercap", true},
		{"GET", "/edev/{id1}/der/{id2}/dercom", true},
		{"GET", "/edev/{id1}/der/{id2}/dercom/{id3}", true},
		{"GET", "/edev/{id1}/der/{id2}/derg", true},
		{"GET", "/edev/{id1}/der/{id2}/derp", true},
		{"GET", "/edev/{id1}/der/{id2}/ders", true},
		{"GET", "/edev/{id1}/der/{id2}/upt", true},
		{"HEAD", "/edev/{id1}/der", true},
		{"HEAD", "/edev/{id1}/der/{id2}", true},
		{"HEAD", "/edev/{id1}/der/{id2}/cdc", true},
		{"HEAD", "/edev/{id1}/der/{id2}/cdp", true},
		{"HEAD", "/edev/{id1}/der/{id2}/dera", true},
		{"HEAD", "/edev/{id1}/der/{id2}/dercap", true},
		{"HEAD", "/edev/{id1}/der/{id2}/dercom", true},
		{"HEAD", "/edev/{id1}/der/{id2}/dercom/{id3}", true},
		{"HEAD", "/edev/{id1}/der/{id2}/derg", true},
		{"HEAD", "/edev/{id1}/der/{id2}/derp", true},
		{"HEAD", "/edev/{id1}/der/{id2}/ders", true},
		{"HEAD", "/edev/{id1}/der/{id2}/upt", true},
		{"POST", "/edev/{id1}/der", true},
		{"POST", "/edev/{id1}/der/{id2}", true},
		{"POST", "/edev/{id1}/der/{id2}/cdc", true},
		{"POST", "/edev/{id1}/der/{id2}/cdp", true},
		{"POST", "/edev/{id1}/der/{id2}/dera", true},
		{"POST", "/edev/{id1}/der/{id2}/dercap", true},
		{"POST", "/edev/{id1}/der/{id2}/dercom", true},
		{"POST", "/edev/{id1}/der/{id2}/dercom/{id3}", true},
		{"POST", "/edev/{id1}/der/{id2}/derg", true},
		{"POST", "/edev/{id1}/der/{id2}/derp", true},
		{"POST", "/edev/{id1}/der/{id2}/ders", true},
		{"POST", "/edev/{id1}/der/{id2}/upt", true},
		{"PUT", "/edev/{id1}/der", true},
		{"PUT", "/edev/{id1}/der/{id2}", true},
		{"PUT", "/edev/{id1}/der/{id2}/cdc", true},
		{"PUT", "/edev/{id1}/der/{id2}/cdp", true},
		{"PUT", "/edev/{id1}/der/{id2}/dera", true},
		{"PUT", "/edev/{id1}/der/{id2}/dercap", true},
		{"PUT", "/edev/{id1}/der/{id2}/dercom", true},
		{"PUT", "/edev/{id1}/der/{id2}/dercom/{id3}", true},
		{"PUT", "/edev/{id1}/der/{id2}/derg", true},
		{"PUT", "/edev/{id1}/der/{id2}/derp", true},
		{"PUT", "/edev/{id1}/der/{id2}/ders", true},
		{"PUT", "/edev/{id1}/der/{id2}/upt", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerDerRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /edev/{id1}/der", http.HandlerFunc(h.DELETEDERList))
	mux.Handle("DELETE /edev/{id1}/der/{id2}", http.HandlerFunc(h.DELETEDER))
	mux.Handle("DELETE /edev/{id1}/der/{id2}/cdc", http.HandlerFunc(h.DELETECurrentDERControlsList))
	mux.Handle("DELETE /edev/{id1}/der/{id2}/cdp", http.HandlerFunc(h.DELETECurrentDERProgramList))
	mux.Handle("DELETE /edev/{id1}/der/{id2}/dera", http.HandlerFunc(h.DELETEDERAvailabilityList))
	mux.Handle("DELETE /edev/{id1}/der/{id2}/dercap", http.HandlerFunc(h.DELETEDERCapability))
	mux.Handle("DELETE /edev/{id1}/der/{id2}/dercom", http.HandlerFunc(h.DELETEDERComponentList))
	mux.Handle("DELETE /edev/{id1}/der/{id2}/dercom/{id3}", http.HandlerFunc(h.DELETEDERComponent))
	mux.Handle("DELETE /edev/{id1}/der/{id2}/derg", http.HandlerFunc(h.DELETEDERSettings))
	mux.Handle("DELETE /edev/{id1}/der/{id2}/derp", http.HandlerFunc(h.DELETEDERProgramList))
	mux.Handle("DELETE /edev/{id1}/der/{id2}/ders", http.HandlerFunc(h.DELETEDERStatus))
	mux.Handle("DELETE /edev/{id1}/der/{id2}/upt", http.HandlerFunc(h.DELETEUsagePointList))
	mux.Handle("GET /edev/{id1}/der", http.HandlerFunc(h.GETDERList))
	mux.Handle("GET /edev/{id1}/der/{id2}", http.HandlerFunc(h.GETDER))
	mux.Handle("GET /edev/{id1}/der/{id2}/cdc", http.HandlerFunc(h.GETCurrentDERControlsList))
	mux.Handle("GET /edev/{id1}/der/{id2}/cdp", http.HandlerFunc(h.GETCurrentDERProgramList))
	mux.Handle("GET /edev/{id1}/der/{id2}/dera", http.HandlerFunc(h.GETDERAvailabilityList))
	mux.Handle("GET /edev/{id1}/der/{id2}/dercap", http.HandlerFunc(h.GETDERCapability))
	mux.Handle("GET /edev/{id1}/der/{id2}/dercom", http.HandlerFunc(h.GETDERComponentList))
	mux.Handle("GET /edev/{id1}/der/{id2}/dercom/{id3}", http.HandlerFunc(h.GETDERComponent))
	mux.Handle("GET /edev/{id1}/der/{id2}/derg", http.HandlerFunc(h.GETDERSettings))
	mux.Handle("GET /edev/{id1}/der/{id2}/derp", http.HandlerFunc(h.GETDERProgramList))
	mux.Handle("GET /edev/{id1}/der/{id2}/ders", http.HandlerFunc(h.GETDERStatus))
	mux.Handle("GET /edev/{id1}/der/{id2}/upt", http.HandlerFunc(h.GETUsagePointList))
	mux.Handle("HEAD /edev/{id1}/der", http.HandlerFunc(h.HEADDERList))
	mux.Handle("HEAD /edev/{id1}/der/{id2}", http.HandlerFunc(h.HEADDER))
	mux.Handle("HEAD /edev/{id1}/der/{id2}/cdc", http.HandlerFunc(h.HEADCurrentDERControlsList))
	mux.Handle("HEAD /edev/{id1}/der/{id2}/cdp", http.HandlerFunc(h.HEADCurrentDERProgramList))
	mux.Handle("HEAD /edev/{id1}/der/{id2}/dera", http.HandlerFunc(h.HEADDERAvailabilityList))
	mux.Handle("HEAD /edev/{id1}/der/{id2}/dercap", http.HandlerFunc(h.HEADDERCapability))
	mux.Handle("HEAD /edev/{id1}/der/{id2}/dercom", http.HandlerFunc(h.HEADDERComponentList))
	mux.Handle("HEAD /edev/{id1}/der/{id2}/dercom/{id3}", http.HandlerFunc(h.HEADDERComponent))
	mux.Handle("HEAD /edev/{id1}/der/{id2}/derg", http.HandlerFunc(h.HEADDERSettings))
	mux.Handle("HEAD /edev/{id1}/der/{id2}/derp", http.HandlerFunc(h.HEADDERProgramList))
	mux.Handle("HEAD /edev/{id1}/der/{id2}/ders", http.HandlerFunc(h.HEADDERStatus))
	mux.Handle("HEAD /edev/{id1}/der/{id2}/upt", http.HandlerFunc(h.HEADUsagePointList))
	mux.Handle("POST /edev/{id1}/der", http.HandlerFunc(h.POSTDERList))
	mux.Handle("POST /edev/{id1}/der/{id2}", http.HandlerFunc(h.POSTDER))
	mux.Handle("POST /edev/{id1}/der/{id2}/cdc", http.HandlerFunc(h.POSTCurrentDERControlsList))
	mux.Handle("POST /edev/{id1}/der/{id2}/cdp", http.HandlerFunc(h.POSTCurrentDERProgramList))
	mux.Handle("POST /edev/{id1}/der/{id2}/dera", http.HandlerFunc(h.POSTDERAvailabilityList))
	mux.Handle("POST /edev/{id1}/der/{id2}/dercap", http.HandlerFunc(h.POSTDERCapability))
	mux.Handle("POST /edev/{id1}/der/{id2}/dercom", http.HandlerFunc(h.POSTDERComponentList))
	mux.Handle("POST /edev/{id1}/der/{id2}/dercom/{id3}", http.HandlerFunc(h.POSTDERComponent))
	mux.Handle("POST /edev/{id1}/der/{id2}/derg", http.HandlerFunc(h.POSTDERSettings))
	mux.Handle("POST /edev/{id1}/der/{id2}/derp", http.HandlerFunc(h.POSTDERProgramList))
	mux.Handle("POST /edev/{id1}/der/{id2}/ders", http.HandlerFunc(h.POSTDERStatus))
	mux.Handle("POST /edev/{id1}/der/{id2}/upt", http.HandlerFunc(h.POSTUsagePointList))
	mux.Handle("PUT /edev/{id1}/der", http.HandlerFunc(h.PUTDERList))
	mux.Handle("PUT /edev/{id1}/der/{id2}", http.HandlerFunc(h.PUTDER))
	mux.Handle("PUT /edev/{id1}/der/{id2}/cdc", http.HandlerFunc(h.PUTCurrentDERControlsList))
	mux.Handle("PUT /edev/{id1}/der/{id2}/cdp", http.HandlerFunc(h.PUTCurrentDERProgramList))
	mux.Handle("PUT /edev/{id1}/der/{id2}/dera", http.HandlerFunc(h.PUTDERAvailabilityList))
	mux.Handle("PUT /edev/{id1}/der/{id2}/dercap", http.HandlerFunc(h.PUTDERCapability))
	mux.Handle("PUT /edev/{id1}/der/{id2}/dercom", http.HandlerFunc(h.PUTDERComponentList))
	mux.Handle("PUT /edev/{id1}/der/{id2}/dercom/{id3}", http.HandlerFunc(h.PUTDERComponent))
	mux.Handle("PUT /edev/{id1}/der/{id2}/derg", http.HandlerFunc(h.PUTDERSettings))
	mux.Handle("PUT /edev/{id1}/der/{id2}/derp", http.HandlerFunc(h.PUTDERProgramList))
	mux.Handle("PUT /edev/{id1}/der/{id2}/ders", http.HandlerFunc(h.PUTDERStatus))
	mux.Handle("PUT /edev/{id1}/der/{id2}/upt", http.HandlerFunc(h.PUTUsagePointList))
}
