// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/DER/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestDerRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerDerRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/der_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	helper.RegisterExpectedRoutes(expectations)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestDerPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/der": nil,
		"/der/{id1}": {"id1"},
		"/der/{id1}/cdc": {"id1"},
		"/der/{id1}/cdp": {"id1"},
		"/der/{id1}/dera": {"id1"},
		"/der/{id1}/dercap": {"id1"},
		"/der/{id1}/dercom": {"id1"},
		"/der/{id1}/dercom/{id2}": {"id1", "id2"},
		"/der/{id1}/derg": {"id1"},
		"/der/{id1}/derp": {"id1"},
		"/der/{id1}/ders": {"id1"},
		"/der/{id1}/upt": {"id1"},
		"/derp": nil,
		"/derp/{id1}": {"id1"},
		"/derp/{id1}/actderc": {"id1"},
		"/derp/{id1}/dc": {"id1"},
		"/derp/{id1}/dc/{id2}": {"id1", "id2"},
		"/derp/{id1}/dderc": {"id1"},
		"/derp/{id1}/derc": {"id1"},
		"/derp/{id1}/derc/{id2}": {"id1", "id2"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestDerHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerDerRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/derp", true},
		{"DELETE", "/derp/{id1}", true},
		{"DELETE", "/derp/{id1}/actderc", true},
		{"DELETE", "/derp/{id1}/dc", true},
		{"DELETE", "/derp/{id1}/dc/{id2}", true},
		{"DELETE", "/derp/{id1}/dderc", true},
		{"DELETE", "/derp/{id1}/derc", true},
		{"DELETE", "/derp/{id1}/derc/{id2}", true},
		{"DELETE", "/der", true},
		{"DELETE", "/der/{id1}", true},
		{"DELETE", "/der/{id1}/cdc", true},
		{"DELETE", "/der/{id1}/cdp", true},
		{"DELETE", "/der/{id1}/dera", true},
		{"DELETE", "/der/{id1}/dercap", true},
		{"DELETE", "/der/{id1}/dercom", true},
		{"DELETE", "/der/{id1}/dercom/{id2}", true},
		{"DELETE", "/der/{id1}/derg", true},
		{"DELETE", "/der/{id1}/derp", true},
		{"DELETE", "/der/{id1}/ders", true},
		{"DELETE", "/der/{id1}/upt", true},
		{"GET", "/derp", true},
		{"GET", "/derp/{id1}", true},
		{"GET", "/derp/{id1}/actderc", true},
		{"GET", "/derp/{id1}/dc", true},
		{"GET", "/derp/{id1}/dc/{id2}", true},
		{"GET", "/derp/{id1}/dderc", true},
		{"GET", "/derp/{id1}/derc", true},
		{"GET", "/derp/{id1}/derc/{id2}", true},
		{"GET", "/der", true},
		{"GET", "/der/{id1}", true},
		{"GET", "/der/{id1}/cdc", true},
		{"GET", "/der/{id1}/cdp", true},
		{"GET", "/der/{id1}/dera", true},
		{"GET", "/der/{id1}/dercap", true},
		{"GET", "/der/{id1}/dercom", true},
		{"GET", "/der/{id1}/dercom/{id2}", true},
		{"GET", "/der/{id1}/derg", true},
		{"GET", "/der/{id1}/derp", true},
		{"GET", "/der/{id1}/ders", true},
		{"GET", "/der/{id1}/upt", true},
		{"HEAD", "/derp", true},
		{"HEAD", "/derp/{id1}", true},
		{"HEAD", "/derp/{id1}/actderc", true},
		{"HEAD", "/derp/{id1}/dc", true},
		{"HEAD", "/derp/{id1}/dc/{id2}", true},
		{"HEAD", "/derp/{id1}/dderc", true},
		{"HEAD", "/derp/{id1}/derc", true},
		{"HEAD", "/derp/{id1}/derc/{id2}", true},
		{"HEAD", "/der", true},
		{"HEAD", "/der/{id1}", true},
		{"HEAD", "/der/{id1}/cdc", true},
		{"HEAD", "/der/{id1}/cdp", true},
		{"HEAD", "/der/{id1}/dera", true},
		{"HEAD", "/der/{id1}/dercap", true},
		{"HEAD", "/der/{id1}/dercom", true},
		{"HEAD", "/der/{id1}/dercom/{id2}", true},
		{"HEAD", "/der/{id1}/derg", true},
		{"HEAD", "/der/{id1}/derp", true},
		{"HEAD", "/der/{id1}/ders", true},
		{"HEAD", "/der/{id1}/upt", true},
		{"POST", "/derp", true},
		{"POST", "/derp/{id1}", true},
		{"POST", "/derp/{id1}/actderc", true},
		{"POST", "/derp/{id1}/dc", true},
		{"POST", "/derp/{id1}/dc/{id2}", true},
		{"POST", "/derp/{id1}/dderc", true},
		{"POST", "/derp/{id1}/derc", true},
		{"POST", "/derp/{id1}/derc/{id2}", true},
		{"POST", "/der", true},
		{"POST", "/der/{id1}", true},
		{"POST", "/der/{id1}/cdc", true},
		{"POST", "/der/{id1}/cdp", true},
		{"POST", "/der/{id1}/dera", true},
		{"POST", "/der/{id1}/dercap", true},
		{"POST", "/der/{id1}/dercom", true},
		{"POST", "/der/{id1}/dercom/{id2}", true},
		{"POST", "/der/{id1}/derg", true},
		{"POST", "/der/{id1}/derp", true},
		{"POST", "/der/{id1}/ders", true},
		{"POST", "/der/{id1}/upt", true},
		{"PUT", "/derp", true},
		{"PUT", "/derp/{id1}", true},
		{"PUT", "/derp/{id1}/actderc", true},
		{"PUT", "/derp/{id1}/dc", true},
		{"PUT", "/derp/{id1}/dc/{id2}", true},
		{"PUT", "/derp/{id1}/dderc", true},
		{"PUT", "/derp/{id1}/derc", true},
		{"PUT", "/derp/{id1}/derc/{id2}", true},
		{"PUT", "/der", true},
		{"PUT", "/der/{id1}", true},
		{"PUT", "/der/{id1}/cdc", true},
		{"PUT", "/der/{id1}/cdp", true},
		{"PUT", "/der/{id1}/dera", true},
		{"PUT", "/der/{id1}/dercap", true},
		{"PUT", "/der/{id1}/dercom", true},
		{"PUT", "/der/{id1}/dercom/{id2}", true},
		{"PUT", "/der/{id1}/derg", true},
		{"PUT", "/der/{id1}/derp", true},
		{"PUT", "/der/{id1}/ders", true},
		{"PUT", "/der/{id1}/upt", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerDerRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /derp", http.HandlerFunc(h.DELETEDERProgramList))
	mux.Handle("DELETE /derp/{id1}", http.HandlerFunc(h.DELETEDERProgram))
	mux.Handle("DELETE /derp/{id1}/actderc", http.HandlerFunc(h.DELETEActiveDERControlList))
	mux.Handle("DELETE /derp/{id1}/dc", http.HandlerFunc(h.DELETEDERCurveList))
	mux.Handle("DELETE /derp/{id1}/dc/{id2}", http.HandlerFunc(h.DELETEDERCurve))
	mux.Handle("DELETE /derp/{id1}/dderc", http.HandlerFunc(h.DELETEDefaultDERControl))
	mux.Handle("DELETE /derp/{id1}/derc", http.HandlerFunc(h.DELETEDERControlList))
	mux.Handle("DELETE /derp/{id1}/derc/{id2}", http.HandlerFunc(h.DELETEDERControl))
	mux.Handle("DELETE /der", http.HandlerFunc(h.DELETEDERList))
	mux.Handle("DELETE /der/{id1}", http.HandlerFunc(h.DELETEDER))
	mux.Handle("DELETE /der/{id1}/cdc", http.HandlerFunc(h.DELETECurrentDERControls))
	mux.Handle("DELETE /der/{id1}/cdp", http.HandlerFunc(h.DELETECurrentDERProgram))
	mux.Handle("DELETE /der/{id1}/dera", http.HandlerFunc(h.DELETEDERAvailability))
	mux.Handle("DELETE /der/{id1}/dercap", http.HandlerFunc(h.DELETEDERCapability))
	mux.Handle("DELETE /der/{id1}/dercom", http.HandlerFunc(h.DELETEDERComponentList))
	mux.Handle("DELETE /der/{id1}/dercom/{id2}", http.HandlerFunc(h.DELETEDERComponent))
	mux.Handle("DELETE /der/{id1}/derg", http.HandlerFunc(h.DELETEDERSettings))
	mux.Handle("DELETE /der/{id1}/derp", http.HandlerFunc(h.DELETEAssociatedDERProgramList))
	mux.Handle("DELETE /der/{id1}/ders", http.HandlerFunc(h.DELETEDERStatus))
	mux.Handle("DELETE /der/{id1}/upt", http.HandlerFunc(h.DELETEAssociatedUsagePoint))
	mux.Handle("GET /derp", http.HandlerFunc(h.GETDERProgramList))
	mux.Handle("GET /derp/{id1}", http.HandlerFunc(h.GETDERProgram))
	mux.Handle("GET /derp/{id1}/actderc", http.HandlerFunc(h.GETActiveDERControlList))
	mux.Handle("GET /derp/{id1}/dc", http.HandlerFunc(h.GETDERCurveList))
	mux.Handle("GET /derp/{id1}/dc/{id2}", http.HandlerFunc(h.GETDERCurve))
	mux.Handle("GET /derp/{id1}/dderc", http.HandlerFunc(h.GETDefaultDERControl))
	mux.Handle("GET /derp/{id1}/derc", http.HandlerFunc(h.GETDERControlList))
	mux.Handle("GET /derp/{id1}/derc/{id2}", http.HandlerFunc(h.GETDERControl))
	mux.Handle("GET /der", http.HandlerFunc(h.GETDERList))
	mux.Handle("GET /der/{id1}", http.HandlerFunc(h.GETDER))
	mux.Handle("GET /der/{id1}/cdc", http.HandlerFunc(h.GETCurrentDERControls))
	mux.Handle("GET /der/{id1}/cdp", http.HandlerFunc(h.GETCurrentDERProgram))
	mux.Handle("GET /der/{id1}/dera", http.HandlerFunc(h.GETDERAvailability))
	mux.Handle("GET /der/{id1}/dercap", http.HandlerFunc(h.GETDERCapability))
	mux.Handle("GET /der/{id1}/dercom", http.HandlerFunc(h.GETDERComponentList))
	mux.Handle("GET /der/{id1}/dercom/{id2}", http.HandlerFunc(h.GETDERComponent))
	mux.Handle("GET /der/{id1}/derg", http.HandlerFunc(h.GETDERSettings))
	mux.Handle("GET /der/{id1}/derp", http.HandlerFunc(h.GETAssociatedDERProgramList))
	mux.Handle("GET /der/{id1}/ders", http.HandlerFunc(h.GETDERStatus))
	mux.Handle("GET /der/{id1}/upt", http.HandlerFunc(h.GETAssociatedUsagePoint))
	mux.Handle("HEAD /derp", http.HandlerFunc(h.HEADDERProgramList))
	mux.Handle("HEAD /derp/{id1}", http.HandlerFunc(h.HEADDERProgram))
	mux.Handle("HEAD /derp/{id1}/actderc", http.HandlerFunc(h.HEADActiveDERControlList))
	mux.Handle("HEAD /derp/{id1}/dc", http.HandlerFunc(h.HEADDERCurveList))
	mux.Handle("HEAD /derp/{id1}/dc/{id2}", http.HandlerFunc(h.HEADDERCurve))
	mux.Handle("HEAD /derp/{id1}/dderc", http.HandlerFunc(h.HEADDefaultDERControl))
	mux.Handle("HEAD /derp/{id1}/derc", http.HandlerFunc(h.HEADDERControlList))
	mux.Handle("HEAD /derp/{id1}/derc/{id2}", http.HandlerFunc(h.HEADDERControl))
	mux.Handle("HEAD /der", http.HandlerFunc(h.HEADDERList))
	mux.Handle("HEAD /der/{id1}", http.HandlerFunc(h.HEADDER))
	mux.Handle("HEAD /der/{id1}/cdc", http.HandlerFunc(h.HEADCurrentDERControls))
	mux.Handle("HEAD /der/{id1}/cdp", http.HandlerFunc(h.HEADCurrentDERProgram))
	mux.Handle("HEAD /der/{id1}/dera", http.HandlerFunc(h.HEADDERAvailability))
	mux.Handle("HEAD /der/{id1}/dercap", http.HandlerFunc(h.HEADDERCapability))
	mux.Handle("HEAD /der/{id1}/dercom", http.HandlerFunc(h.HEADDERComponentList))
	mux.Handle("HEAD /der/{id1}/dercom/{id2}", http.HandlerFunc(h.HEADDERComponent))
	mux.Handle("HEAD /der/{id1}/derg", http.HandlerFunc(h.HEADDERSettings))
	mux.Handle("HEAD /der/{id1}/derp", http.HandlerFunc(h.HEADAssociatedDERProgramList))
	mux.Handle("HEAD /der/{id1}/ders", http.HandlerFunc(h.HEADDERStatus))
	mux.Handle("HEAD /der/{id1}/upt", http.HandlerFunc(h.HEADAssociatedUsagePoint))
	mux.Handle("POST /derp", http.HandlerFunc(h.POSTDERProgramList))
	mux.Handle("POST /derp/{id1}", http.HandlerFunc(h.POSTDERProgram))
	mux.Handle("POST /derp/{id1}/actderc", http.HandlerFunc(h.POSTActiveDERControlList))
	mux.Handle("POST /derp/{id1}/dc", http.HandlerFunc(h.POSTDERCurveList))
	mux.Handle("POST /derp/{id1}/dc/{id2}", http.HandlerFunc(h.POSTDERCurve))
	mux.Handle("POST /derp/{id1}/dderc", http.HandlerFunc(h.POSTDefaultDERControl))
	mux.Handle("POST /derp/{id1}/derc", http.HandlerFunc(h.POSTDERControlList))
	mux.Handle("POST /derp/{id1}/derc/{id2}", http.HandlerFunc(h.POSTDERControl))
	mux.Handle("POST /der", http.HandlerFunc(h.POSTDERList))
	mux.Handle("POST /der/{id1}", http.HandlerFunc(h.POSTDER))
	mux.Handle("POST /der/{id1}/cdc", http.HandlerFunc(h.POSTCurrentDERControls))
	mux.Handle("POST /der/{id1}/cdp", http.HandlerFunc(h.POSTCurrentDERProgram))
	mux.Handle("POST /der/{id1}/dera", http.HandlerFunc(h.POSTDERAvailability))
	mux.Handle("POST /der/{id1}/dercap", http.HandlerFunc(h.POSTDERCapability))
	mux.Handle("POST /der/{id1}/dercom", http.HandlerFunc(h.POSTDERComponentList))
	mux.Handle("POST /der/{id1}/dercom/{id2}", http.HandlerFunc(h.POSTDERComponent))
	mux.Handle("POST /der/{id1}/derg", http.HandlerFunc(h.POSTDERSettings))
	mux.Handle("POST /der/{id1}/derp", http.HandlerFunc(h.POSTAssociatedDERProgramList))
	mux.Handle("POST /der/{id1}/ders", http.HandlerFunc(h.POSTDERStatus))
	mux.Handle("POST /der/{id1}/upt", http.HandlerFunc(h.POSTAssociatedUsagePoint))
	mux.Handle("PUT /derp", http.HandlerFunc(h.PUTDERProgramList))
	mux.Handle("PUT /derp/{id1}", http.HandlerFunc(h.PUTDERProgram))
	mux.Handle("PUT /derp/{id1}/actderc", http.HandlerFunc(h.PUTActiveDERControlList))
	mux.Handle("PUT /derp/{id1}/dc", http.HandlerFunc(h.PUTDERCurveList))
	mux.Handle("PUT /derp/{id1}/dc/{id2}", http.HandlerFunc(h.PUTDERCurve))
	mux.Handle("PUT /derp/{id1}/dderc", http.HandlerFunc(h.PUTDefaultDERControl))
	mux.Handle("PUT /derp/{id1}/derc", http.HandlerFunc(h.PUTDERControlList))
	mux.Handle("PUT /derp/{id1}/derc/{id2}", http.HandlerFunc(h.PUTDERControl))
	mux.Handle("PUT /der", http.HandlerFunc(h.PUTDERList))
	mux.Handle("PUT /der/{id1}", http.HandlerFunc(h.PUTDER))
	mux.Handle("PUT /der/{id1}/cdc", http.HandlerFunc(h.PUTCurrentDERControls))
	mux.Handle("PUT /der/{id1}/cdp", http.HandlerFunc(h.PUTCurrentDERProgram))
	mux.Handle("PUT /der/{id1}/dera", http.HandlerFunc(h.PUTDERAvailability))
	mux.Handle("PUT /der/{id1}/dercap", http.HandlerFunc(h.PUTDERCapability))
	mux.Handle("PUT /der/{id1}/dercom", http.HandlerFunc(h.PUTDERComponentList))
	mux.Handle("PUT /der/{id1}/dercom/{id2}", http.HandlerFunc(h.PUTDERComponent))
	mux.Handle("PUT /der/{id1}/derg", http.HandlerFunc(h.PUTDERSettings))
	mux.Handle("PUT /der/{id1}/derp", http.HandlerFunc(h.PUTAssociatedDERProgramList))
	mux.Handle("PUT /der/{id1}/ders", http.HandlerFunc(h.PUTDERStatus))
	mux.Handle("PUT /der/{id1}/upt", http.HandlerFunc(h.PUTAssociatedUsagePoint))
}
