// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/Bill/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestBillRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerBillRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/bill_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	helper.RegisterExpectedRoutes(expectations)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestBillPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/bill": nil,
		"/bill/{id1}": {"id1"},
		"/bill/{id1}/ca": {"id1"},
		"/bill/{id1}/ca/{id2}": {"id1", "id2"},
		"/bill/{id1}/ca/{id2}/actbp": {"id1", "id2"},
		"/bill/{id1}/ca/{id2}/bp": {"id1", "id2"},
		"/bill/{id1}/ca/{id2}/bp/{id3}": {"id1", "id2", "id3"},
		"/bill/{id1}/ca/{id2}/pro": {"id1", "id2"},
		"/bill/{id1}/ca/{id2}/pro/{id3}": {"id1", "id2", "id3"},
		"/bill/{id1}/ca/{id2}/tar": {"id1", "id2"},
		"/bill/{id1}/ca/{id2}/tar/{id3}": {"id1", "id2", "id3"},
		"/bill/{id1}/ca/{id2}/ver": {"id1", "id2"},
		"/bill/{id1}/ca/{id2}/ver/{id3}": {"id1", "id2", "id3"},
		"/bill/{id1}/ss": {"id1"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestBillHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerBillRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/bill", true},
		{"DELETE", "/bill/{id1}", true},
		{"DELETE", "/bill/{id1}/ca", true},
		{"DELETE", "/bill/{id1}/ca/{id2}", true},
		{"DELETE", "/bill/{id1}/ca/{id2}/actbp", true},
		{"DELETE", "/bill/{id1}/ca/{id2}/bp", true},
		{"DELETE", "/bill/{id1}/ca/{id2}/bp/{id3}", true},
		{"DELETE", "/bill/{id1}/ca/{id2}/pro", true},
		{"DELETE", "/bill/{id1}/ca/{id2}/pro/{id3}", true},
		{"DELETE", "/bill/{id1}/ca/{id2}/tar", true},
		{"DELETE", "/bill/{id1}/ca/{id2}/tar/{id3}", true},
		{"DELETE", "/bill/{id1}/ca/{id2}/ver", true},
		{"DELETE", "/bill/{id1}/ca/{id2}/ver/{id3}", true},
		{"DELETE", "/bill/{id1}/ss", true},
		{"GET", "/bill", true},
		{"GET", "/bill/{id1}", true},
		{"GET", "/bill/{id1}/ca", true},
		{"GET", "/bill/{id1}/ca/{id2}", true},
		{"GET", "/bill/{id1}/ca/{id2}/actbp", true},
		{"GET", "/bill/{id1}/ca/{id2}/bp", true},
		{"GET", "/bill/{id1}/ca/{id2}/bp/{id3}", true},
		{"GET", "/bill/{id1}/ca/{id2}/pro", true},
		{"GET", "/bill/{id1}/ca/{id2}/pro/{id3}", true},
		{"GET", "/bill/{id1}/ca/{id2}/tar", true},
		{"GET", "/bill/{id1}/ca/{id2}/tar/{id3}", true},
		{"GET", "/bill/{id1}/ca/{id2}/ver", true},
		{"GET", "/bill/{id1}/ca/{id2}/ver/{id3}", true},
		{"GET", "/bill/{id1}/ss", true},
		{"HEAD", "/bill", true},
		{"HEAD", "/bill/{id1}", true},
		{"HEAD", "/bill/{id1}/ca", true},
		{"HEAD", "/bill/{id1}/ca/{id2}", true},
		{"HEAD", "/bill/{id1}/ca/{id2}/actbp", true},
		{"HEAD", "/bill/{id1}/ca/{id2}/bp", true},
		{"HEAD", "/bill/{id1}/ca/{id2}/bp/{id3}", true},
		{"HEAD", "/bill/{id1}/ca/{id2}/pro", true},
		{"HEAD", "/bill/{id1}/ca/{id2}/pro/{id3}", true},
		{"HEAD", "/bill/{id1}/ca/{id2}/tar", true},
		{"HEAD", "/bill/{id1}/ca/{id2}/tar/{id3}", true},
		{"HEAD", "/bill/{id1}/ca/{id2}/ver", true},
		{"HEAD", "/bill/{id1}/ca/{id2}/ver/{id3}", true},
		{"HEAD", "/bill/{id1}/ss", true},
		{"POST", "/bill", true},
		{"POST", "/bill/{id1}", true},
		{"POST", "/bill/{id1}/ca", true},
		{"POST", "/bill/{id1}/ca/{id2}", true},
		{"POST", "/bill/{id1}/ca/{id2}/actbp", true},
		{"POST", "/bill/{id1}/ca/{id2}/bp", true},
		{"POST", "/bill/{id1}/ca/{id2}/bp/{id3}", true},
		{"POST", "/bill/{id1}/ca/{id2}/pro", true},
		{"POST", "/bill/{id1}/ca/{id2}/pro/{id3}", true},
		{"POST", "/bill/{id1}/ca/{id2}/tar", true},
		{"POST", "/bill/{id1}/ca/{id2}/tar/{id3}", true},
		{"POST", "/bill/{id1}/ca/{id2}/ver", true},
		{"POST", "/bill/{id1}/ca/{id2}/ver/{id3}", true},
		{"POST", "/bill/{id1}/ss", true},
		{"PUT", "/bill", true},
		{"PUT", "/bill/{id1}", true},
		{"PUT", "/bill/{id1}/ca", true},
		{"PUT", "/bill/{id1}/ca/{id2}", true},
		{"PUT", "/bill/{id1}/ca/{id2}/actbp", true},
		{"PUT", "/bill/{id1}/ca/{id2}/bp", true},
		{"PUT", "/bill/{id1}/ca/{id2}/bp/{id3}", true},
		{"PUT", "/bill/{id1}/ca/{id2}/pro", true},
		{"PUT", "/bill/{id1}/ca/{id2}/pro/{id3}", true},
		{"PUT", "/bill/{id1}/ca/{id2}/tar", true},
		{"PUT", "/bill/{id1}/ca/{id2}/tar/{id3}", true},
		{"PUT", "/bill/{id1}/ca/{id2}/ver", true},
		{"PUT", "/bill/{id1}/ca/{id2}/ver/{id3}", true},
		{"PUT", "/bill/{id1}/ss", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerBillRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /bill", http.HandlerFunc(h.DELETECustomerAccountList))
	mux.Handle("DELETE /bill/{id1}", http.HandlerFunc(h.DELETECustomerAccount))
	mux.Handle("DELETE /bill/{id1}/ca", http.HandlerFunc(h.DELETECustomerAgreementList))
	mux.Handle("DELETE /bill/{id1}/ca/{id2}", http.HandlerFunc(h.DELETECustomerAgreement))
	mux.Handle("DELETE /bill/{id1}/ca/{id2}/actbp", http.HandlerFunc(h.DELETEActiveBillingPeriodList))
	mux.Handle("DELETE /bill/{id1}/ca/{id2}/bp", http.HandlerFunc(h.DELETEBillingPeriodList))
	mux.Handle("DELETE /bill/{id1}/ca/{id2}/bp/{id3}", http.HandlerFunc(h.DELETEBillingPeriod))
	mux.Handle("DELETE /bill/{id1}/ca/{id2}/pro", http.HandlerFunc(h.DELETEProjectionReadingList))
	mux.Handle("DELETE /bill/{id1}/ca/{id2}/pro/{id3}", http.HandlerFunc(h.DELETEProjectionReading))
	mux.Handle("DELETE /bill/{id1}/ca/{id2}/tar", http.HandlerFunc(h.DELETETargetReadingList))
	mux.Handle("DELETE /bill/{id1}/ca/{id2}/tar/{id3}", http.HandlerFunc(h.DELETETargetReading))
	mux.Handle("DELETE /bill/{id1}/ca/{id2}/ver", http.HandlerFunc(h.DELETEHistoricalReadingList))
	mux.Handle("DELETE /bill/{id1}/ca/{id2}/ver/{id3}", http.HandlerFunc(h.DELETEHistoricalReading))
	mux.Handle("DELETE /bill/{id1}/ss", http.HandlerFunc(h.DELETEServiceSupplier))
	mux.Handle("GET /bill", http.HandlerFunc(h.GETCustomerAccountList))
	mux.Handle("GET /bill/{id1}", http.HandlerFunc(h.GETCustomerAccount))
	mux.Handle("GET /bill/{id1}/ca", http.HandlerFunc(h.GETCustomerAgreementList))
	mux.Handle("GET /bill/{id1}/ca/{id2}", http.HandlerFunc(h.GETCustomerAgreement))
	mux.Handle("GET /bill/{id1}/ca/{id2}/actbp", http.HandlerFunc(h.GETActiveBillingPeriodList))
	mux.Handle("GET /bill/{id1}/ca/{id2}/bp", http.HandlerFunc(h.GETBillingPeriodList))
	mux.Handle("GET /bill/{id1}/ca/{id2}/bp/{id3}", http.HandlerFunc(h.GETBillingPeriod))
	mux.Handle("GET /bill/{id1}/ca/{id2}/pro", http.HandlerFunc(h.GETProjectionReadingList))
	mux.Handle("GET /bill/{id1}/ca/{id2}/pro/{id3}", http.HandlerFunc(h.GETProjectionReading))
	mux.Handle("GET /bill/{id1}/ca/{id2}/tar", http.HandlerFunc(h.GETTargetReadingList))
	mux.Handle("GET /bill/{id1}/ca/{id2}/tar/{id3}", http.HandlerFunc(h.GETTargetReading))
	mux.Handle("GET /bill/{id1}/ca/{id2}/ver", http.HandlerFunc(h.GETHistoricalReadingList))
	mux.Handle("GET /bill/{id1}/ca/{id2}/ver/{id3}", http.HandlerFunc(h.GETHistoricalReading))
	mux.Handle("GET /bill/{id1}/ss", http.HandlerFunc(h.GETServiceSupplier))
	mux.Handle("HEAD /bill", http.HandlerFunc(h.HEADCustomerAccountList))
	mux.Handle("HEAD /bill/{id1}", http.HandlerFunc(h.HEADCustomerAccount))
	mux.Handle("HEAD /bill/{id1}/ca", http.HandlerFunc(h.HEADCustomerAgreementList))
	mux.Handle("HEAD /bill/{id1}/ca/{id2}", http.HandlerFunc(h.HEADCustomerAgreement))
	mux.Handle("HEAD /bill/{id1}/ca/{id2}/actbp", http.HandlerFunc(h.HEADActiveBillingPeriodList))
	mux.Handle("HEAD /bill/{id1}/ca/{id2}/bp", http.HandlerFunc(h.HEADBillingPeriodList))
	mux.Handle("HEAD /bill/{id1}/ca/{id2}/bp/{id3}", http.HandlerFunc(h.HEADBillingPeriod))
	mux.Handle("HEAD /bill/{id1}/ca/{id2}/pro", http.HandlerFunc(h.HEADProjectionReadingList))
	mux.Handle("HEAD /bill/{id1}/ca/{id2}/pro/{id3}", http.HandlerFunc(h.HEADProjectionReading))
	mux.Handle("HEAD /bill/{id1}/ca/{id2}/tar", http.HandlerFunc(h.HEADTargetReadingList))
	mux.Handle("HEAD /bill/{id1}/ca/{id2}/tar/{id3}", http.HandlerFunc(h.HEADTargetReading))
	mux.Handle("HEAD /bill/{id1}/ca/{id2}/ver", http.HandlerFunc(h.HEADHistoricalReadingList))
	mux.Handle("HEAD /bill/{id1}/ca/{id2}/ver/{id3}", http.HandlerFunc(h.HEADHistoricalReading))
	mux.Handle("HEAD /bill/{id1}/ss", http.HandlerFunc(h.HEADServiceSupplier))
	mux.Handle("POST /bill", http.HandlerFunc(h.POSTCustomerAccountList))
	mux.Handle("POST /bill/{id1}", http.HandlerFunc(h.POSTCustomerAccount))
	mux.Handle("POST /bill/{id1}/ca", http.HandlerFunc(h.POSTCustomerAgreementList))
	mux.Handle("POST /bill/{id1}/ca/{id2}", http.HandlerFunc(h.POSTCustomerAgreement))
	mux.Handle("POST /bill/{id1}/ca/{id2}/actbp", http.HandlerFunc(h.POSTActiveBillingPeriodList))
	mux.Handle("POST /bill/{id1}/ca/{id2}/bp", http.HandlerFunc(h.POSTBillingPeriodList))
	mux.Handle("POST /bill/{id1}/ca/{id2}/bp/{id3}", http.HandlerFunc(h.POSTBillingPeriod))
	mux.Handle("POST /bill/{id1}/ca/{id2}/pro", http.HandlerFunc(h.POSTProjectionReadingList))
	mux.Handle("POST /bill/{id1}/ca/{id2}/pro/{id3}", http.HandlerFunc(h.POSTProjectionReading))
	mux.Handle("POST /bill/{id1}/ca/{id2}/tar", http.HandlerFunc(h.POSTTargetReadingList))
	mux.Handle("POST /bill/{id1}/ca/{id2}/tar/{id3}", http.HandlerFunc(h.POSTTargetReading))
	mux.Handle("POST /bill/{id1}/ca/{id2}/ver", http.HandlerFunc(h.POSTHistoricalReadingList))
	mux.Handle("POST /bill/{id1}/ca/{id2}/ver/{id3}", http.HandlerFunc(h.POSTHistoricalReading))
	mux.Handle("POST /bill/{id1}/ss", http.HandlerFunc(h.POSTServiceSupplier))
	mux.Handle("PUT /bill", http.HandlerFunc(h.PUTCustomerAccountList))
	mux.Handle("PUT /bill/{id1}", http.HandlerFunc(h.PUTCustomerAccount))
	mux.Handle("PUT /bill/{id1}/ca", http.HandlerFunc(h.PUTCustomerAgreementList))
	mux.Handle("PUT /bill/{id1}/ca/{id2}", http.HandlerFunc(h.PUTCustomerAgreement))
	mux.Handle("PUT /bill/{id1}/ca/{id2}/actbp", http.HandlerFunc(h.PUTActiveBillingPeriodList))
	mux.Handle("PUT /bill/{id1}/ca/{id2}/bp", http.HandlerFunc(h.PUTBillingPeriodList))
	mux.Handle("PUT /bill/{id1}/ca/{id2}/bp/{id3}", http.HandlerFunc(h.PUTBillingPeriod))
	mux.Handle("PUT /bill/{id1}/ca/{id2}/pro", http.HandlerFunc(h.PUTProjectionReadingList))
	mux.Handle("PUT /bill/{id1}/ca/{id2}/pro/{id3}", http.HandlerFunc(h.PUTProjectionReading))
	mux.Handle("PUT /bill/{id1}/ca/{id2}/tar", http.HandlerFunc(h.PUTTargetReadingList))
	mux.Handle("PUT /bill/{id1}/ca/{id2}/tar/{id3}", http.HandlerFunc(h.PUTTargetReading))
	mux.Handle("PUT /bill/{id1}/ca/{id2}/ver", http.HandlerFunc(h.PUTHistoricalReadingList))
	mux.Handle("PUT /bill/{id1}/ca/{id2}/ver/{id3}", http.HandlerFunc(h.PUTHistoricalReading))
	mux.Handle("PUT /bill/{id1}/ss", http.HandlerFunc(h.PUTServiceSupplier))
}
