// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/EDevice/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestEdevRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerEdevRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/edev_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	helper.RegisterExpectedRoutes(expectations)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestEdevPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/edev": nil,
		"/edev/{id1}": {"id1"},
		"/edev/{id1}/adev": {"id1"},
		"/edev/{id1}/adev/{id2}": {"id1", "id2"},
		"/edev/{id1}/aggp": {"id1"},
		"/edev/{id1}/cfg": {"id1"},
		"/edev/{id1}/cfg/prcfg": {"id1"},
		"/edev/{id1}/cfg/prcfg/{id2}": {"id1", "id2"},
		"/edev/{id1}/di": {"id1"},
		"/edev/{id1}/di/loc": {"id1"},
		"/edev/{id1}/di/loc/{id2}": {"id1", "id2"},
		"/edev/{id1}/dstat": {"id1"},
		"/edev/{id1}/fs": {"id1"},
		"/edev/{id1}/fsa": {"id1"},
		"/edev/{id1}/fsa/{id2}": {"id1", "id2"},
		"/edev/{id1}/lel": {"id1"},
		"/edev/{id1}/lel/{id2}": {"id1", "id2"},
		"/edev/{id1}/lsl": {"id1"},
		"/edev/{id1}/lsl/{id2}": {"id1", "id2"},
		"/edev/{id1}/ns": {"id1"},
		"/edev/{id1}/ns/{id2}": {"id1", "id2"},
		"/edev/{id1}/ns/{id2}/addr": {"id1", "id2"},
		"/edev/{id1}/ns/{id2}/addr/{id3}": {"id1", "id2", "id3"},
		"/edev/{id1}/ns/{id2}/addr/{id3}/rpl": {"id1", "id2", "id3"},
		"/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}": {"id1", "id2", "id3", "id4"},
		"/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt": {"id1", "id2", "id3", "id4"},
		"/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}": {"id1", "id2", "id3", "id4", "id5"},
		"/edev/{id1}/ns/{id2}/ll": {"id1", "id2"},
		"/edev/{id1}/ns/{id2}/ll/{id3}": {"id1", "id2", "id3"},
		"/edev/{id1}/ns/{id2}/ll/{id3}/nbh": {"id1", "id2", "id3"},
		"/edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}": {"id1", "id2", "id3", "id4"},
		"/edev/{id1}/prxy": {"id1"},
		"/edev/{id1}/prxy/{id2}": {"id1", "id2"},
		"/edev/{id1}/ps": {"id1"},
		"/edev/{id1}/rg": {"id1"},
		"/edev/{id1}/sub": {"id1"},
		"/edev/{id1}/sub/{id2}": {"id1", "id2"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestEdevHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerEdevRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/edev", true},
		{"DELETE", "/edev/{id1}", true},
		{"DELETE", "/edev/{id1}/adev", true},
		{"DELETE", "/edev/{id1}/adev/{id2}", true},
		{"DELETE", "/edev/{id1}/aggp", true},
		{"DELETE", "/edev/{id1}/cfg", true},
		{"DELETE", "/edev/{id1}/cfg/prcfg", true},
		{"DELETE", "/edev/{id1}/cfg/prcfg/{id2}", true},
		{"DELETE", "/edev/{id1}/di", true},
		{"DELETE", "/edev/{id1}/di/loc", true},
		{"DELETE", "/edev/{id1}/di/loc/{id2}", true},
		{"DELETE", "/edev/{id1}/dstat", true},
		{"DELETE", "/edev/{id1}/fs", true},
		{"DELETE", "/edev/{id1}/fsa", true},
		{"DELETE", "/edev/{id1}/fsa/{id2}", true},
		{"DELETE", "/edev/{id1}/lel", true},
		{"DELETE", "/edev/{id1}/lel/{id2}", true},
		{"DELETE", "/edev/{id1}/lsl", true},
		{"DELETE", "/edev/{id1}/lsl/{id2}", true},
		{"DELETE", "/edev/{id1}/ns", true},
		{"DELETE", "/edev/{id1}/ns/{id2}", true},
		{"DELETE", "/edev/{id1}/ns/{id2}/addr", true},
		{"DELETE", "/edev/{id1}/ns/{id2}/addr/{id3}", true},
		{"DELETE", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl", true},
		{"DELETE", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", true},
		{"DELETE", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", true},
		{"DELETE", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", true},
		{"DELETE", "/edev/{id1}/ns/{id2}/ll", true},
		{"DELETE", "/edev/{id1}/ns/{id2}/ll/{id3}", true},
		{"DELETE", "/edev/{id1}/ns/{id2}/ll/{id3}/nbh", true},
		{"DELETE", "/edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", true},
		{"DELETE", "/edev/{id1}/prxy", true},
		{"DELETE", "/edev/{id1}/prxy/{id2}", true},
		{"DELETE", "/edev/{id1}/ps", true},
		{"DELETE", "/edev/{id1}/rg", true},
		{"DELETE", "/edev/{id1}/sub", true},
		{"DELETE", "/edev/{id1}/sub/{id2}", true},
		{"GET", "/edev", true},
		{"GET", "/edev/{id1}", true},
		{"GET", "/edev/{id1}/adev", true},
		{"GET", "/edev/{id1}/adev/{id2}", true},
		{"GET", "/edev/{id1}/aggp", true},
		{"GET", "/edev/{id1}/cfg", true},
		{"GET", "/edev/{id1}/cfg/prcfg", true},
		{"GET", "/edev/{id1}/cfg/prcfg/{id2}", true},
		{"GET", "/edev/{id1}/di", true},
		{"GET", "/edev/{id1}/di/loc", true},
		{"GET", "/edev/{id1}/di/loc/{id2}", true},
		{"GET", "/edev/{id1}/dstat", true},
		{"GET", "/edev/{id1}/fs", true},
		{"GET", "/edev/{id1}/fsa", true},
		{"GET", "/edev/{id1}/fsa/{id2}", true},
		{"GET", "/edev/{id1}/lel", true},
		{"GET", "/edev/{id1}/lel/{id2}", true},
		{"GET", "/edev/{id1}/lsl", true},
		{"GET", "/edev/{id1}/lsl/{id2}", true},
		{"GET", "/edev/{id1}/ns", true},
		{"GET", "/edev/{id1}/ns/{id2}", true},
		{"GET", "/edev/{id1}/ns/{id2}/addr", true},
		{"GET", "/edev/{id1}/ns/{id2}/addr/{id3}", true},
		{"GET", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl", true},
		{"GET", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", true},
		{"GET", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", true},
		{"GET", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", true},
		{"GET", "/edev/{id1}/ns/{id2}/ll", true},
		{"GET", "/edev/{id1}/ns/{id2}/ll/{id3}", true},
		{"GET", "/edev/{id1}/ns/{id2}/ll/{id3}/nbh", true},
		{"GET", "/edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", true},
		{"GET", "/edev/{id1}/prxy", true},
		{"GET", "/edev/{id1}/prxy/{id2}", true},
		{"GET", "/edev/{id1}/ps", true},
		{"GET", "/edev/{id1}/rg", true},
		{"GET", "/edev/{id1}/sub", true},
		{"GET", "/edev/{id1}/sub/{id2}", true},
		{"HEAD", "/edev", true},
		{"HEAD", "/edev/{id1}", true},
		{"HEAD", "/edev/{id1}/adev", true},
		{"HEAD", "/edev/{id1}/adev/{id2}", true},
		{"HEAD", "/edev/{id1}/aggp", true},
		{"HEAD", "/edev/{id1}/cfg", true},
		{"HEAD", "/edev/{id1}/cfg/prcfg", true},
		{"HEAD", "/edev/{id1}/cfg/prcfg/{id2}", true},
		{"HEAD", "/edev/{id1}/di", true},
		{"HEAD", "/edev/{id1}/di/loc", true},
		{"HEAD", "/edev/{id1}/di/loc/{id2}", true},
		{"HEAD", "/edev/{id1}/dstat", true},
		{"HEAD", "/edev/{id1}/fs", true},
		{"HEAD", "/edev/{id1}/fsa", true},
		{"HEAD", "/edev/{id1}/fsa/{id2}", true},
		{"HEAD", "/edev/{id1}/lel", true},
		{"HEAD", "/edev/{id1}/lel/{id2}", true},
		{"HEAD", "/edev/{id1}/lsl", true},
		{"HEAD", "/edev/{id1}/lsl/{id2}", true},
		{"HEAD", "/edev/{id1}/ns", true},
		{"HEAD", "/edev/{id1}/ns/{id2}", true},
		{"HEAD", "/edev/{id1}/ns/{id2}/addr", true},
		{"HEAD", "/edev/{id1}/ns/{id2}/addr/{id3}", true},
		{"HEAD", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl", true},
		{"HEAD", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", true},
		{"HEAD", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", true},
		{"HEAD", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", true},
		{"HEAD", "/edev/{id1}/ns/{id2}/ll", true},
		{"HEAD", "/edev/{id1}/ns/{id2}/ll/{id3}", true},
		{"HEAD", "/edev/{id1}/ns/{id2}/ll/{id3}/nbh", true},
		{"HEAD", "/edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", true},
		{"HEAD", "/edev/{id1}/prxy", true},
		{"HEAD", "/edev/{id1}/prxy/{id2}", true},
		{"HEAD", "/edev/{id1}/ps", true},
		{"HEAD", "/edev/{id1}/rg", true},
		{"HEAD", "/edev/{id1}/sub", true},
		{"HEAD", "/edev/{id1}/sub/{id2}", true},
		{"POST", "/edev", true},
		{"POST", "/edev/{id1}", true},
		{"POST", "/edev/{id1}/adev", true},
		{"POST", "/edev/{id1}/adev/{id2}", true},
		{"POST", "/edev/{id1}/aggp", true},
		{"POST", "/edev/{id1}/cfg", true},
		{"POST", "/edev/{id1}/cfg/prcfg", true},
		{"POST", "/edev/{id1}/cfg/prcfg/{id2}", true},
		{"POST", "/edev/{id1}/di", true},
		{"POST", "/edev/{id1}/di/loc", true},
		{"POST", "/edev/{id1}/di/loc/{id2}", true},
		{"POST", "/edev/{id1}/dstat", true},
		{"POST", "/edev/{id1}/fs", true},
		{"POST", "/edev/{id1}/fsa", true},
		{"POST", "/edev/{id1}/fsa/{id2}", true},
		{"POST", "/edev/{id1}/lel", true},
		{"POST", "/edev/{id1}/lel/{id2}", true},
		{"POST", "/edev/{id1}/lsl", true},
		{"POST", "/edev/{id1}/lsl/{id2}", true},
		{"POST", "/edev/{id1}/ns", true},
		{"POST", "/edev/{id1}/ns/{id2}", true},
		{"POST", "/edev/{id1}/ns/{id2}/addr", true},
		{"POST", "/edev/{id1}/ns/{id2}/addr/{id3}", true},
		{"POST", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl", true},
		{"POST", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", true},
		{"POST", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", true},
		{"POST", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", true},
		{"POST", "/edev/{id1}/ns/{id2}/ll", true},
		{"POST", "/edev/{id1}/ns/{id2}/ll/{id3}", true},
		{"POST", "/edev/{id1}/ns/{id2}/ll/{id3}/nbh", true},
		{"POST", "/edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", true},
		{"POST", "/edev/{id1}/prxy", true},
		{"POST", "/edev/{id1}/prxy/{id2}", true},
		{"POST", "/edev/{id1}/ps", true},
		{"POST", "/edev/{id1}/rg", true},
		{"POST", "/edev/{id1}/sub", true},
		{"POST", "/edev/{id1}/sub/{id2}", true},
		{"PUT", "/edev", true},
		{"PUT", "/edev/{id1}", true},
		{"PUT", "/edev/{id1}/adev", true},
		{"PUT", "/edev/{id1}/adev/{id2}", true},
		{"PUT", "/edev/{id1}/aggp", true},
		{"PUT", "/edev/{id1}/cfg", true},
		{"PUT", "/edev/{id1}/cfg/prcfg", true},
		{"PUT", "/edev/{id1}/cfg/prcfg/{id2}", true},
		{"PUT", "/edev/{id1}/di", true},
		{"PUT", "/edev/{id1}/di/loc", true},
		{"PUT", "/edev/{id1}/di/loc/{id2}", true},
		{"PUT", "/edev/{id1}/dstat", true},
		{"PUT", "/edev/{id1}/fs", true},
		{"PUT", "/edev/{id1}/fsa", true},
		{"PUT", "/edev/{id1}/fsa/{id2}", true},
		{"PUT", "/edev/{id1}/lel", true},
		{"PUT", "/edev/{id1}/lel/{id2}", true},
		{"PUT", "/edev/{id1}/lsl", true},
		{"PUT", "/edev/{id1}/lsl/{id2}", true},
		{"PUT", "/edev/{id1}/ns", true},
		{"PUT", "/edev/{id1}/ns/{id2}", true},
		{"PUT", "/edev/{id1}/ns/{id2}/addr", true},
		{"PUT", "/edev/{id1}/ns/{id2}/addr/{id3}", true},
		{"PUT", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl", true},
		{"PUT", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", true},
		{"PUT", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", true},
		{"PUT", "/edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", true},
		{"PUT", "/edev/{id1}/ns/{id2}/ll", true},
		{"PUT", "/edev/{id1}/ns/{id2}/ll/{id3}", true},
		{"PUT", "/edev/{id1}/ns/{id2}/ll/{id3}/nbh", true},
		{"PUT", "/edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", true},
		{"PUT", "/edev/{id1}/prxy", true},
		{"PUT", "/edev/{id1}/prxy/{id2}", true},
		{"PUT", "/edev/{id1}/ps", true},
		{"PUT", "/edev/{id1}/rg", true},
		{"PUT", "/edev/{id1}/sub", true},
		{"PUT", "/edev/{id1}/sub/{id2}", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerEdevRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /edev", http.HandlerFunc(h.DELETEEndDeviceList))
	mux.Handle("DELETE /edev/{id1}", http.HandlerFunc(h.DELETEEndDevice))
	mux.Handle("DELETE /edev/{id1}/adev", http.HandlerFunc(h.DELETEAggregatedDeviceList))
	mux.Handle("DELETE /edev/{id1}/adev/{id2}", http.HandlerFunc(h.DELETEAggregatedDevice))
	mux.Handle("DELETE /edev/{id1}/aggp", http.HandlerFunc(h.DELETEAggregationPriority))
	mux.Handle("DELETE /edev/{id1}/cfg", http.HandlerFunc(h.DELETEConfiguration))
	mux.Handle("DELETE /edev/{id1}/cfg/prcfg", http.HandlerFunc(h.DELETEPriceResponseCfgList))
	mux.Handle("DELETE /edev/{id1}/cfg/prcfg/{id2}", http.HandlerFunc(h.DELETEPriceResponseCfg))
	mux.Handle("DELETE /edev/{id1}/di", http.HandlerFunc(h.DELETEDeviceInformation))
	mux.Handle("DELETE /edev/{id1}/di/loc", http.HandlerFunc(h.DELETESupportedLocaleList))
	mux.Handle("DELETE /edev/{id1}/di/loc/{id2}", http.HandlerFunc(h.DELETESupportedLocale))
	mux.Handle("DELETE /edev/{id1}/dstat", http.HandlerFunc(h.DELETEDeviceStatus))
	mux.Handle("DELETE /edev/{id1}/fs", http.HandlerFunc(h.DELETEFileStatus))
	mux.Handle("DELETE /edev/{id1}/fsa", http.HandlerFunc(h.DELETEFunctionSetAssignmentsList))
	mux.Handle("DELETE /edev/{id1}/fsa/{id2}", http.HandlerFunc(h.DELETEFunctionSetAssignments))
	mux.Handle("DELETE /edev/{id1}/lel", http.HandlerFunc(h.DELETELogEventList))
	mux.Handle("DELETE /edev/{id1}/lel/{id2}", http.HandlerFunc(h.DELETELogEvent))
	mux.Handle("DELETE /edev/{id1}/lsl", http.HandlerFunc(h.DELETELoadShedAvailabilityList))
	mux.Handle("DELETE /edev/{id1}/lsl/{id2}", http.HandlerFunc(h.DELETELoadShedAvailability))
	mux.Handle("DELETE /edev/{id1}/ns", http.HandlerFunc(h.DELETEIPInterfaceList))
	mux.Handle("DELETE /edev/{id1}/ns/{id2}", http.HandlerFunc(h.DELETEIPInterface))
	mux.Handle("DELETE /edev/{id1}/ns/{id2}/addr", http.HandlerFunc(h.DELETEIPAddrList))
	mux.Handle("DELETE /edev/{id1}/ns/{id2}/addr/{id3}", http.HandlerFunc(h.DELETEIPAddr))
	mux.Handle("DELETE /edev/{id1}/ns/{id2}/addr/{id3}/rpl", http.HandlerFunc(h.DELETERPLInstanceList))
	mux.Handle("DELETE /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", http.HandlerFunc(h.DELETERPLInstance))
	mux.Handle("DELETE /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", http.HandlerFunc(h.DELETERPLSourceRoutesList))
	mux.Handle("DELETE /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", http.HandlerFunc(h.DELETERPLSourceRoutes))
	mux.Handle("DELETE /edev/{id1}/ns/{id2}/ll", http.HandlerFunc(h.DELETELLInterfaceList))
	mux.Handle("DELETE /edev/{id1}/ns/{id2}/ll/{id3}", http.HandlerFunc(h.DELETELLInterface))
	mux.Handle("DELETE /edev/{id1}/ns/{id2}/ll/{id3}/nbh", http.HandlerFunc(h.DELETENeighborList))
	mux.Handle("DELETE /edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", http.HandlerFunc(h.DELETENeighbor))
	mux.Handle("DELETE /edev/{id1}/prxy", http.HandlerFunc(h.DELETEProxiedDeviceList))
	mux.Handle("DELETE /edev/{id1}/prxy/{id2}", http.HandlerFunc(h.DELETEProxiedDevice))
	mux.Handle("DELETE /edev/{id1}/ps", http.HandlerFunc(h.DELETEPowerStatus))
	mux.Handle("DELETE /edev/{id1}/rg", http.HandlerFunc(h.DELETERegistration))
	mux.Handle("DELETE /edev/{id1}/sub", http.HandlerFunc(h.DELETESubscriptionList))
	mux.Handle("DELETE /edev/{id1}/sub/{id2}", http.HandlerFunc(h.DELETESubscription))
	mux.Handle("GET /edev", http.HandlerFunc(h.GETEndDeviceList))
	mux.Handle("GET /edev/{id1}", http.HandlerFunc(h.GETEndDevice))
	mux.Handle("GET /edev/{id1}/adev", http.HandlerFunc(h.GETAggregatedDeviceList))
	mux.Handle("GET /edev/{id1}/adev/{id2}", http.HandlerFunc(h.GETAggregatedDevice))
	mux.Handle("GET /edev/{id1}/aggp", http.HandlerFunc(h.GETAggregationPriority))
	mux.Handle("GET /edev/{id1}/cfg", http.HandlerFunc(h.GETConfiguration))
	mux.Handle("GET /edev/{id1}/cfg/prcfg", http.HandlerFunc(h.GETPriceResponseCfgList))
	mux.Handle("GET /edev/{id1}/cfg/prcfg/{id2}", http.HandlerFunc(h.GETPriceResponseCfg))
	mux.Handle("GET /edev/{id1}/di", http.HandlerFunc(h.GETDeviceInformation))
	mux.Handle("GET /edev/{id1}/di/loc", http.HandlerFunc(h.GETSupportedLocaleList))
	mux.Handle("GET /edev/{id1}/di/loc/{id2}", http.HandlerFunc(h.GETSupportedLocale))
	mux.Handle("GET /edev/{id1}/dstat", http.HandlerFunc(h.GETDeviceStatus))
	mux.Handle("GET /edev/{id1}/fs", http.HandlerFunc(h.GETFileStatus))
	mux.Handle("GET /edev/{id1}/fsa", http.HandlerFunc(h.GETFunctionSetAssignmentsList))
	mux.Handle("GET /edev/{id1}/fsa/{id2}", http.HandlerFunc(h.GETFunctionSetAssignments))
	mux.Handle("GET /edev/{id1}/lel", http.HandlerFunc(h.GETLogEventList))
	mux.Handle("GET /edev/{id1}/lel/{id2}", http.HandlerFunc(h.GETLogEvent))
	mux.Handle("GET /edev/{id1}/lsl", http.HandlerFunc(h.GETLoadShedAvailabilityList))
	mux.Handle("GET /edev/{id1}/lsl/{id2}", http.HandlerFunc(h.GETLoadShedAvailability))
	mux.Handle("GET /edev/{id1}/ns", http.HandlerFunc(h.GETIPInterfaceList))
	mux.Handle("GET /edev/{id1}/ns/{id2}", http.HandlerFunc(h.GETIPInterface))
	mux.Handle("GET /edev/{id1}/ns/{id2}/addr", http.HandlerFunc(h.GETIPAddrList))
	mux.Handle("GET /edev/{id1}/ns/{id2}/addr/{id3}", http.HandlerFunc(h.GETIPAddr))
	mux.Handle("GET /edev/{id1}/ns/{id2}/addr/{id3}/rpl", http.HandlerFunc(h.GETRPLInstanceList))
	mux.Handle("GET /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", http.HandlerFunc(h.GETRPLInstance))
	mux.Handle("GET /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", http.HandlerFunc(h.GETRPLSourceRoutesList))
	mux.Handle("GET /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", http.HandlerFunc(h.GETRPLSourceRoutes))
	mux.Handle("GET /edev/{id1}/ns/{id2}/ll", http.HandlerFunc(h.GETLLInterfaceList))
	mux.Handle("GET /edev/{id1}/ns/{id2}/ll/{id3}", http.HandlerFunc(h.GETLLInterface))
	mux.Handle("GET /edev/{id1}/ns/{id2}/ll/{id3}/nbh", http.HandlerFunc(h.GETNeighborList))
	mux.Handle("GET /edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", http.HandlerFunc(h.GETNeighbor))
	mux.Handle("GET /edev/{id1}/prxy", http.HandlerFunc(h.GETProxiedDeviceList))
	mux.Handle("GET /edev/{id1}/prxy/{id2}", http.HandlerFunc(h.GETProxiedDevice))
	mux.Handle("GET /edev/{id1}/ps", http.HandlerFunc(h.GETPowerStatus))
	mux.Handle("GET /edev/{id1}/rg", http.HandlerFunc(h.GETRegistration))
	mux.Handle("GET /edev/{id1}/sub", http.HandlerFunc(h.GETSubscriptionList))
	mux.Handle("GET /edev/{id1}/sub/{id2}", http.HandlerFunc(h.GETSubscription))
	mux.Handle("HEAD /edev", http.HandlerFunc(h.HEADEndDeviceList))
	mux.Handle("HEAD /edev/{id1}", http.HandlerFunc(h.HEADEndDevice))
	mux.Handle("HEAD /edev/{id1}/adev", http.HandlerFunc(h.HEADAggregatedDeviceList))
	mux.Handle("HEAD /edev/{id1}/adev/{id2}", http.HandlerFunc(h.HEADAggregatedDevice))
	mux.Handle("HEAD /edev/{id1}/aggp", http.HandlerFunc(h.HEADAggregationPriority))
	mux.Handle("HEAD /edev/{id1}/cfg", http.HandlerFunc(h.HEADConfiguration))
	mux.Handle("HEAD /edev/{id1}/cfg/prcfg", http.HandlerFunc(h.HEADPriceResponseCfgList))
	mux.Handle("HEAD /edev/{id1}/cfg/prcfg/{id2}", http.HandlerFunc(h.HEADPriceResponseCfg))
	mux.Handle("HEAD /edev/{id1}/di", http.HandlerFunc(h.HEADDeviceInformation))
	mux.Handle("HEAD /edev/{id1}/di/loc", http.HandlerFunc(h.HEADSupportedLocaleList))
	mux.Handle("HEAD /edev/{id1}/di/loc/{id2}", http.HandlerFunc(h.HEADSupportedLocale))
	mux.Handle("HEAD /edev/{id1}/dstat", http.HandlerFunc(h.HEADDeviceStatus))
	mux.Handle("HEAD /edev/{id1}/fs", http.HandlerFunc(h.HEADFileStatus))
	mux.Handle("HEAD /edev/{id1}/fsa", http.HandlerFunc(h.HEADFunctionSetAssignmentsList))
	mux.Handle("HEAD /edev/{id1}/fsa/{id2}", http.HandlerFunc(h.HEADFunctionSetAssignments))
	mux.Handle("HEAD /edev/{id1}/lel", http.HandlerFunc(h.HEADLogEventList))
	mux.Handle("HEAD /edev/{id1}/lel/{id2}", http.HandlerFunc(h.HEADLogEvent))
	mux.Handle("HEAD /edev/{id1}/lsl", http.HandlerFunc(h.HEADLoadShedAvailabilityList))
	mux.Handle("HEAD /edev/{id1}/lsl/{id2}", http.HandlerFunc(h.HEADLoadShedAvailability))
	mux.Handle("HEAD /edev/{id1}/ns", http.HandlerFunc(h.HEADIPInterfaceList))
	mux.Handle("HEAD /edev/{id1}/ns/{id2}", http.HandlerFunc(h.HEADIPInterface))
	mux.Handle("HEAD /edev/{id1}/ns/{id2}/addr", http.HandlerFunc(h.HEADIPAddrList))
	mux.Handle("HEAD /edev/{id1}/ns/{id2}/addr/{id3}", http.HandlerFunc(h.HEADIPAddr))
	mux.Handle("HEAD /edev/{id1}/ns/{id2}/addr/{id3}/rpl", http.HandlerFunc(h.HEADRPLInstanceList))
	mux.Handle("HEAD /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", http.HandlerFunc(h.HEADRPLInstance))
	mux.Handle("HEAD /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", http.HandlerFunc(h.HEADRPLSourceRoutesList))
	mux.Handle("HEAD /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", http.HandlerFunc(h.HEADRPLSourceRoutes))
	mux.Handle("HEAD /edev/{id1}/ns/{id2}/ll", http.HandlerFunc(h.HEADLLInterfaceList))
	mux.Handle("HEAD /edev/{id1}/ns/{id2}/ll/{id3}", http.HandlerFunc(h.HEADLLInterface))
	mux.Handle("HEAD /edev/{id1}/ns/{id2}/ll/{id3}/nbh", http.HandlerFunc(h.HEADNeighborList))
	mux.Handle("HEAD /edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", http.HandlerFunc(h.HEADNeighbor))
	mux.Handle("HEAD /edev/{id1}/prxy", http.HandlerFunc(h.HEADProxiedDeviceList))
	mux.Handle("HEAD /edev/{id1}/prxy/{id2}", http.HandlerFunc(h.HEADProxiedDevice))
	mux.Handle("HEAD /edev/{id1}/ps", http.HandlerFunc(h.HEADPowerStatus))
	mux.Handle("HEAD /edev/{id1}/rg", http.HandlerFunc(h.HEADRegistration))
	mux.Handle("HEAD /edev/{id1}/sub", http.HandlerFunc(h.HEADSubscriptionList))
	mux.Handle("HEAD /edev/{id1}/sub/{id2}", http.HandlerFunc(h.HEADSubscription))
	mux.Handle("POST /edev", http.HandlerFunc(h.POSTEndDeviceList))
	mux.Handle("POST /edev/{id1}", http.HandlerFunc(h.POSTEndDevice))
	mux.Handle("POST /edev/{id1}/adev", http.HandlerFunc(h.POSTAggregatedDeviceList))
	mux.Handle("POST /edev/{id1}/adev/{id2}", http.HandlerFunc(h.POSTAggregatedDevice))
	mux.Handle("POST /edev/{id1}/aggp", http.HandlerFunc(h.POSTAggregationPriority))
	mux.Handle("POST /edev/{id1}/cfg", http.HandlerFunc(h.POSTConfiguration))
	mux.Handle("POST /edev/{id1}/cfg/prcfg", http.HandlerFunc(h.POSTPriceResponseCfgList))
	mux.Handle("POST /edev/{id1}/cfg/prcfg/{id2}", http.HandlerFunc(h.POSTPriceResponseCfg))
	mux.Handle("POST /edev/{id1}/di", http.HandlerFunc(h.POSTDeviceInformation))
	mux.Handle("POST /edev/{id1}/di/loc", http.HandlerFunc(h.POSTSupportedLocaleList))
	mux.Handle("POST /edev/{id1}/di/loc/{id2}", http.HandlerFunc(h.POSTSupportedLocale))
	mux.Handle("POST /edev/{id1}/dstat", http.HandlerFunc(h.POSTDeviceStatus))
	mux.Handle("POST /edev/{id1}/fs", http.HandlerFunc(h.POSTFileStatus))
	mux.Handle("POST /edev/{id1}/fsa", http.HandlerFunc(h.POSTFunctionSetAssignmentsList))
	mux.Handle("POST /edev/{id1}/fsa/{id2}", http.HandlerFunc(h.POSTFunctionSetAssignments))
	mux.Handle("POST /edev/{id1}/lel", http.HandlerFunc(h.POSTLogEventList))
	mux.Handle("POST /edev/{id1}/lel/{id2}", http.HandlerFunc(h.POSTLogEvent))
	mux.Handle("POST /edev/{id1}/lsl", http.HandlerFunc(h.POSTLoadShedAvailabilityList))
	mux.Handle("POST /edev/{id1}/lsl/{id2}", http.HandlerFunc(h.POSTLoadShedAvailability))
	mux.Handle("POST /edev/{id1}/ns", http.HandlerFunc(h.POSTIPInterfaceList))
	mux.Handle("POST /edev/{id1}/ns/{id2}", http.HandlerFunc(h.POSTIPInterface))
	mux.Handle("POST /edev/{id1}/ns/{id2}/addr", http.HandlerFunc(h.POSTIPAddrList))
	mux.Handle("POST /edev/{id1}/ns/{id2}/addr/{id3}", http.HandlerFunc(h.POSTIPAddr))
	mux.Handle("POST /edev/{id1}/ns/{id2}/addr/{id3}/rpl", http.HandlerFunc(h.POSTRPLInstanceList))
	mux.Handle("POST /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", http.HandlerFunc(h.POSTRPLInstance))
	mux.Handle("POST /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", http.HandlerFunc(h.POSTRPLSourceRoutesList))
	mux.Handle("POST /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", http.HandlerFunc(h.POSTRPLSourceRoutes))
	mux.Handle("POST /edev/{id1}/ns/{id2}/ll", http.HandlerFunc(h.POSTLLInterfaceList))
	mux.Handle("POST /edev/{id1}/ns/{id2}/ll/{id3}", http.HandlerFunc(h.POSTLLInterface))
	mux.Handle("POST /edev/{id1}/ns/{id2}/ll/{id3}/nbh", http.HandlerFunc(h.POSTNeighborList))
	mux.Handle("POST /edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", http.HandlerFunc(h.POSTNeighbor))
	mux.Handle("POST /edev/{id1}/prxy", http.HandlerFunc(h.POSTProxiedDeviceList))
	mux.Handle("POST /edev/{id1}/prxy/{id2}", http.HandlerFunc(h.POSTProxiedDevice))
	mux.Handle("POST /edev/{id1}/ps", http.HandlerFunc(h.POSTPowerStatus))
	mux.Handle("POST /edev/{id1}/rg", http.HandlerFunc(h.POSTRegistration))
	mux.Handle("POST /edev/{id1}/sub", http.HandlerFunc(h.POSTSubscriptionList))
	mux.Handle("POST /edev/{id1}/sub/{id2}", http.HandlerFunc(h.POSTSubscription))
	mux.Handle("PUT /edev", http.HandlerFunc(h.PUTEndDeviceList))
	mux.Handle("PUT /edev/{id1}", http.HandlerFunc(h.PUTEndDevice))
	mux.Handle("PUT /edev/{id1}/adev", http.HandlerFunc(h.PUTAggregatedDeviceList))
	mux.Handle("PUT /edev/{id1}/adev/{id2}", http.HandlerFunc(h.PUTAggregatedDevice))
	mux.Handle("PUT /edev/{id1}/aggp", http.HandlerFunc(h.PUTAggregationPriority))
	mux.Handle("PUT /edev/{id1}/cfg", http.HandlerFunc(h.PUTConfiguration))
	mux.Handle("PUT /edev/{id1}/cfg/prcfg", http.HandlerFunc(h.PUTPriceResponseCfgList))
	mux.Handle("PUT /edev/{id1}/cfg/prcfg/{id2}", http.HandlerFunc(h.PUTPriceResponseCfg))
	mux.Handle("PUT /edev/{id1}/di", http.HandlerFunc(h.PUTDeviceInformation))
	mux.Handle("PUT /edev/{id1}/di/loc", http.HandlerFunc(h.PUTSupportedLocaleList))
	mux.Handle("PUT /edev/{id1}/di/loc/{id2}", http.HandlerFunc(h.PUTSupportedLocale))
	mux.Handle("PUT /edev/{id1}/dstat", http.HandlerFunc(h.PUTDeviceStatus))
	mux.Handle("PUT /edev/{id1}/fs", http.HandlerFunc(h.PUTFileStatus))
	mux.Handle("PUT /edev/{id1}/fsa", http.HandlerFunc(h.PUTFunctionSetAssignmentsList))
	mux.Handle("PUT /edev/{id1}/fsa/{id2}", http.HandlerFunc(h.PUTFunctionSetAssignments))
	mux.Handle("PUT /edev/{id1}/lel", http.HandlerFunc(h.PUTLogEventList))
	mux.Handle("PUT /edev/{id1}/lel/{id2}", http.HandlerFunc(h.PUTLogEvent))
	mux.Handle("PUT /edev/{id1}/lsl", http.HandlerFunc(h.PUTLoadShedAvailabilityList))
	mux.Handle("PUT /edev/{id1}/lsl/{id2}", http.HandlerFunc(h.PUTLoadShedAvailability))
	mux.Handle("PUT /edev/{id1}/ns", http.HandlerFunc(h.PUTIPInterfaceList))
	mux.Handle("PUT /edev/{id1}/ns/{id2}", http.HandlerFunc(h.PUTIPInterface))
	mux.Handle("PUT /edev/{id1}/ns/{id2}/addr", http.HandlerFunc(h.PUTIPAddrList))
	mux.Handle("PUT /edev/{id1}/ns/{id2}/addr/{id3}", http.HandlerFunc(h.PUTIPAddr))
	mux.Handle("PUT /edev/{id1}/ns/{id2}/addr/{id3}/rpl", http.HandlerFunc(h.PUTRPLInstanceList))
	mux.Handle("PUT /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", http.HandlerFunc(h.PUTRPLInstance))
	mux.Handle("PUT /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", http.HandlerFunc(h.PUTRPLSourceRoutesList))
	mux.Handle("PUT /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", http.HandlerFunc(h.PUTRPLSourceRoutes))
	mux.Handle("PUT /edev/{id1}/ns/{id2}/ll", http.HandlerFunc(h.PUTLLInterfaceList))
	mux.Handle("PUT /edev/{id1}/ns/{id2}/ll/{id3}", http.HandlerFunc(h.PUTLLInterface))
	mux.Handle("PUT /edev/{id1}/ns/{id2}/ll/{id3}/nbh", http.HandlerFunc(h.PUTNeighborList))
	mux.Handle("PUT /edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", http.HandlerFunc(h.PUTNeighbor))
	mux.Handle("PUT /edev/{id1}/prxy", http.HandlerFunc(h.PUTProxiedDeviceList))
	mux.Handle("PUT /edev/{id1}/prxy/{id2}", http.HandlerFunc(h.PUTProxiedDevice))
	mux.Handle("PUT /edev/{id1}/ps", http.HandlerFunc(h.PUTPowerStatus))
	mux.Handle("PUT /edev/{id1}/rg", http.HandlerFunc(h.PUTRegistration))
	mux.Handle("PUT /edev/{id1}/sub", http.HandlerFunc(h.PUTSubscriptionList))
	mux.Handle("PUT /edev/{id1}/sub/{id2}", http.HandlerFunc(h.PUTSubscription))
}
