package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"

	"github.com/Tylores/egot/internal/EDevice/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/internal/routes"
	"github.com/Tylores/egot/internal/tlsutil"
)

func main() {
	cfg, err := tlsutil.NewServerConfig("./ssl")
	if err != nil {
		log.Fatal(err)
	}
	server := http.Server{
		Addr:              routes.EDevice,
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       15 * time.Second,
		WriteTimeout:      15 * time.Second,
		IdleTimeout:       60 * time.Second,
		TLSConfig:         cfg,
		Handler:           tlsutil.CertHeaderMiddleware(http.DefaultServeMux),
	}

	reg := registry.New(filepath.Join("data", "registry.db"))
	if err := reg.Load(); err != nil {
		log.Fatal(err)
	}
	defer reg.Close()
	// Auto-populate registry from known client certs
	_ = reg.PopulateFromCertDir("./ssl")

	repo := store.New(filepath.Join("data", "EDevice.db"))
	if err := repo.Load(); err != nil {
		log.Fatal(err)
	}
	defer repo.Close()

	h := handler.NewHandler(repo, reg)
	http.Handle("GET /edev", http.HandlerFunc(h.GETEndDeviceList))
	http.Handle("HEAD /edev", http.HandlerFunc(h.HEADEndDeviceList))
	http.Handle("PUT /edev", http.HandlerFunc(h.PUTEndDeviceList))
	http.Handle("POST /edev", http.HandlerFunc(h.POSTEndDeviceList))
	http.Handle("DELETE /edev", http.HandlerFunc(h.DELETEEndDeviceList))
	http.Handle("GET /edev/{id1}", http.HandlerFunc(h.GETEndDevice))
	http.Handle("HEAD /edev/{id1}", http.HandlerFunc(h.HEADEndDevice))
	http.Handle("PUT /edev/{id1}", http.HandlerFunc(h.PUTEndDevice))
	http.Handle("POST /edev/{id1}", http.HandlerFunc(h.POSTEndDevice))
	http.Handle("DELETE /edev/{id1}", http.HandlerFunc(h.DELETEEndDevice))
	http.Handle("GET /edev/{id1}/rg", http.HandlerFunc(h.GETRegistration))
	http.Handle("HEAD /edev/{id1}/rg", http.HandlerFunc(h.HEADRegistration))
	http.Handle("PUT /edev/{id1}/rg", http.HandlerFunc(h.PUTRegistration))
	http.Handle("POST /edev/{id1}/rg", http.HandlerFunc(h.POSTRegistration))
	http.Handle("DELETE /edev/{id1}/rg", http.HandlerFunc(h.DELETERegistration))
	http.Handle("GET /edev/{id1}/dstat", http.HandlerFunc(h.GETDeviceStatus))
	http.Handle("HEAD /edev/{id1}/dstat", http.HandlerFunc(h.HEADDeviceStatus))
	http.Handle("PUT /edev/{id1}/dstat", http.HandlerFunc(h.PUTDeviceStatus))
	http.Handle("POST /edev/{id1}/dstat", http.HandlerFunc(h.POSTDeviceStatus))
	http.Handle("DELETE /edev/{id1}/dstat", http.HandlerFunc(h.DELETEDeviceStatus))
	http.Handle("GET /edev/{id1}/prxy", http.HandlerFunc(h.GETProxiedDeviceList))
	http.Handle("HEAD /edev/{id1}/prxy", http.HandlerFunc(h.HEADProxiedDeviceList))
	http.Handle("PUT /edev/{id1}/prxy", http.HandlerFunc(h.PUTProxiedDeviceList))
	http.Handle("POST /edev/{id1}/prxy", http.HandlerFunc(h.POSTProxiedDeviceList))
	http.Handle("DELETE /edev/{id1}/prxy", http.HandlerFunc(h.DELETEProxiedDeviceList))
	http.Handle("GET /edev/{id1}/prxy/{id2}", http.HandlerFunc(h.GETProxiedDevice))
	http.Handle("HEAD /edev/{id1}/prxy/{id2}", http.HandlerFunc(h.HEADProxiedDevice))
	http.Handle("PUT /edev/{id1}/prxy/{id2}", http.HandlerFunc(h.PUTProxiedDevice))
	http.Handle("POST /edev/{id1}/prxy/{id2}", http.HandlerFunc(h.POSTProxiedDevice))
	http.Handle("DELETE /edev/{id1}/prxy/{id2}", http.HandlerFunc(h.DELETEProxiedDevice))
	http.Handle("GET /edev/{id1}/aggp", http.HandlerFunc(h.GETAggregationPriority))
	http.Handle("HEAD /edev/{id1}/aggp", http.HandlerFunc(h.HEADAggregationPriority))
	http.Handle("PUT /edev/{id1}/aggp", http.HandlerFunc(h.PUTAggregationPriority))
	http.Handle("POST /edev/{id1}/aggp", http.HandlerFunc(h.POSTAggregationPriority))
	http.Handle("DELETE /edev/{id1}/aggp", http.HandlerFunc(h.DELETEAggregationPriority))
	http.Handle("GET /edev/{id1}/adev", http.HandlerFunc(h.GETAggregatedDeviceList))
	http.Handle("HEAD /edev/{id1}/adev", http.HandlerFunc(h.HEADAggregatedDeviceList))
	http.Handle("PUT /edev/{id1}/adev", http.HandlerFunc(h.PUTAggregatedDeviceList))
	http.Handle("POST /edev/{id1}/adev", http.HandlerFunc(h.POSTAggregatedDeviceList))
	http.Handle("DELETE /edev/{id1}/adev", http.HandlerFunc(h.DELETEAggregatedDeviceList))
	http.Handle("GET /edev/{id1}/adev/{id2}", http.HandlerFunc(h.GETAggregatedDevice))
	http.Handle("HEAD /edev/{id1}/adev/{id2}", http.HandlerFunc(h.HEADAggregatedDevice))
	http.Handle("PUT /edev/{id1}/adev/{id2}", http.HandlerFunc(h.PUTAggregatedDevice))
	http.Handle("POST /edev/{id1}/adev/{id2}", http.HandlerFunc(h.POSTAggregatedDevice))
	http.Handle("DELETE /edev/{id1}/adev/{id2}", http.HandlerFunc(h.DELETEAggregatedDevice))
	http.Handle("GET /edev/{id1}/fsa", http.HandlerFunc(h.GETFunctionSetAssignmentsList))
	http.Handle("HEAD /edev/{id1}/fsa", http.HandlerFunc(h.HEADFunctionSetAssignmentsList))
	http.Handle("PUT /edev/{id1}/fsa", http.HandlerFunc(h.PUTFunctionSetAssignmentsList))
	http.Handle("POST /edev/{id1}/fsa", http.HandlerFunc(h.POSTFunctionSetAssignmentsList))
	http.Handle("DELETE /edev/{id1}/fsa", http.HandlerFunc(h.DELETEFunctionSetAssignmentsList))
	http.Handle("GET /edev/{id1}/fsa/{id2}", http.HandlerFunc(h.GETFunctionSetAssignments))
	http.Handle("HEAD /edev/{id1}/fsa/{id2}", http.HandlerFunc(h.HEADFunctionSetAssignments))
	http.Handle("PUT /edev/{id1}/fsa/{id2}", http.HandlerFunc(h.PUTFunctionSetAssignments))
	http.Handle("POST /edev/{id1}/fsa/{id2}", http.HandlerFunc(h.POSTFunctionSetAssignments))
	http.Handle("DELETE /edev/{id1}/fsa/{id2}", http.HandlerFunc(h.DELETEFunctionSetAssignments))
	http.Handle("GET /edev/{id1}/sub", http.HandlerFunc(h.GETSubscriptionList))
	http.Handle("HEAD /edev/{id1}/sub", http.HandlerFunc(h.HEADSubscriptionList))
	http.Handle("PUT /edev/{id1}/sub", http.HandlerFunc(h.PUTSubscriptionList))
	http.Handle("POST /edev/{id1}/sub", http.HandlerFunc(h.POSTSubscriptionList))
	http.Handle("DELETE /edev/{id1}/sub", http.HandlerFunc(h.DELETESubscriptionList))
	http.Handle("GET /edev/{id1}/sub/{id2}", http.HandlerFunc(h.GETSubscription))
	http.Handle("HEAD /edev/{id1}/sub/{id2}", http.HandlerFunc(h.HEADSubscription))
	http.Handle("PUT /edev/{id1}/sub/{id2}", http.HandlerFunc(h.PUTSubscription))
	http.Handle("POST /edev/{id1}/sub/{id2}", http.HandlerFunc(h.POSTSubscription))
	http.Handle("DELETE /edev/{id1}/sub/{id2}", http.HandlerFunc(h.DELETESubscription))
	http.Handle("GET /edev/{id1}/di", http.HandlerFunc(h.GETDeviceInformation))
	http.Handle("HEAD /edev/{id1}/di", http.HandlerFunc(h.HEADDeviceInformation))
	http.Handle("PUT /edev/{id1}/di", http.HandlerFunc(h.PUTDeviceInformation))
	http.Handle("POST /edev/{id1}/di", http.HandlerFunc(h.POSTDeviceInformation))
	http.Handle("DELETE /edev/{id1}/di", http.HandlerFunc(h.DELETEDeviceInformation))
	http.Handle("GET /edev/{id1}/di/loc", http.HandlerFunc(h.GETSupportedLocaleList))
	http.Handle("HEAD /edev/{id1}/di/loc", http.HandlerFunc(h.HEADSupportedLocaleList))
	http.Handle("PUT /edev/{id1}/di/loc", http.HandlerFunc(h.PUTSupportedLocaleList))
	http.Handle("POST /edev/{id1}/di/loc", http.HandlerFunc(h.POSTSupportedLocaleList))
	http.Handle("DELETE /edev/{id1}/di/loc", http.HandlerFunc(h.DELETESupportedLocaleList))
	http.Handle("GET /edev/{id1}/di/loc/{id2}", http.HandlerFunc(h.GETSupportedLocale))
	http.Handle("HEAD /edev/{id1}/di/loc/{id2}", http.HandlerFunc(h.HEADSupportedLocale))
	http.Handle("PUT /edev/{id1}/di/loc/{id2}", http.HandlerFunc(h.PUTSupportedLocale))
	http.Handle("POST /edev/{id1}/di/loc/{id2}", http.HandlerFunc(h.POSTSupportedLocale))
	http.Handle("DELETE /edev/{id1}/di/loc/{id2}", http.HandlerFunc(h.DELETESupportedLocale))
	http.Handle("GET /edev/{id1}/ps", http.HandlerFunc(h.GETPowerStatus))
	http.Handle("HEAD /edev/{id1}/ps", http.HandlerFunc(h.HEADPowerStatus))
	http.Handle("PUT /edev/{id1}/ps", http.HandlerFunc(h.PUTPowerStatus))
	http.Handle("POST /edev/{id1}/ps", http.HandlerFunc(h.POSTPowerStatus))
	http.Handle("DELETE /edev/{id1}/ps", http.HandlerFunc(h.DELETEPowerStatus))
	http.Handle("GET /edev/{id1}/ns", http.HandlerFunc(h.GETIPInterfaceList))
	http.Handle("HEAD /edev/{id1}/ns", http.HandlerFunc(h.HEADIPInterfaceList))
	http.Handle("PUT /edev/{id1}/ns", http.HandlerFunc(h.PUTIPInterfaceList))
	http.Handle("POST /edev/{id1}/ns", http.HandlerFunc(h.POSTIPInterfaceList))
	http.Handle("DELETE /edev/{id1}/ns", http.HandlerFunc(h.DELETEIPInterfaceList))
	http.Handle("GET /edev/{id1}/ns/{id2}", http.HandlerFunc(h.GETIPInterface))
	http.Handle("HEAD /edev/{id1}/ns/{id2}", http.HandlerFunc(h.HEADIPInterface))
	http.Handle("PUT /edev/{id1}/ns/{id2}", http.HandlerFunc(h.PUTIPInterface))
	http.Handle("POST /edev/{id1}/ns/{id2}", http.HandlerFunc(h.POSTIPInterface))
	http.Handle("DELETE /edev/{id1}/ns/{id2}", http.HandlerFunc(h.DELETEIPInterface))
	http.Handle("GET /edev/{id1}/ns/{id2}/addr", http.HandlerFunc(h.GETIPAddrList))
	http.Handle("HEAD /edev/{id1}/ns/{id2}/addr", http.HandlerFunc(h.HEADIPAddrList))
	http.Handle("PUT /edev/{id1}/ns/{id2}/addr", http.HandlerFunc(h.PUTIPAddrList))
	http.Handle("POST /edev/{id1}/ns/{id2}/addr", http.HandlerFunc(h.POSTIPAddrList))
	http.Handle("DELETE /edev/{id1}/ns/{id2}/addr", http.HandlerFunc(h.DELETEIPAddrList))
	http.Handle("GET /edev/{id1}/ns/{id2}/addr/{id3}", http.HandlerFunc(h.GETIPAddr))
	http.Handle("HEAD /edev/{id1}/ns/{id2}/addr/{id3}", http.HandlerFunc(h.HEADIPAddr))
	http.Handle("PUT /edev/{id1}/ns/{id2}/addr/{id3}", http.HandlerFunc(h.PUTIPAddr))
	http.Handle("POST /edev/{id1}/ns/{id2}/addr/{id3}", http.HandlerFunc(h.POSTIPAddr))
	http.Handle("DELETE /edev/{id1}/ns/{id2}/addr/{id3}", http.HandlerFunc(h.DELETEIPAddr))
	http.Handle("GET /edev/{id1}/ns/{id2}/addr/{id3}/rpl", http.HandlerFunc(h.GETRPLInstanceList))
	http.Handle("HEAD /edev/{id1}/ns/{id2}/addr/{id3}/rpl", http.HandlerFunc(h.HEADRPLInstanceList))
	http.Handle("PUT /edev/{id1}/ns/{id2}/addr/{id3}/rpl", http.HandlerFunc(h.PUTRPLInstanceList))
	http.Handle("POST /edev/{id1}/ns/{id2}/addr/{id3}/rpl", http.HandlerFunc(h.POSTRPLInstanceList))
	http.Handle("DELETE /edev/{id1}/ns/{id2}/addr/{id3}/rpl", http.HandlerFunc(h.DELETERPLInstanceList))
	http.Handle("GET /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", http.HandlerFunc(h.GETRPLInstance))
	http.Handle("HEAD /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", http.HandlerFunc(h.HEADRPLInstance))
	http.Handle("PUT /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", http.HandlerFunc(h.PUTRPLInstance))
	http.Handle("POST /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", http.HandlerFunc(h.POSTRPLInstance))
	http.Handle("DELETE /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}", http.HandlerFunc(h.DELETERPLInstance))
	http.Handle("GET /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", http.HandlerFunc(h.GETRPLSourceRoutesList))
	http.Handle("HEAD /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", http.HandlerFunc(h.HEADRPLSourceRoutesList))
	http.Handle("PUT /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", http.HandlerFunc(h.PUTRPLSourceRoutesList))
	http.Handle("POST /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", http.HandlerFunc(h.POSTRPLSourceRoutesList))
	http.Handle("DELETE /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt", http.HandlerFunc(h.DELETERPLSourceRoutesList))
	http.Handle("GET /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", http.HandlerFunc(h.GETRPLSourceRoutes))
	http.Handle("HEAD /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", http.HandlerFunc(h.HEADRPLSourceRoutes))
	http.Handle("PUT /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", http.HandlerFunc(h.PUTRPLSourceRoutes))
	http.Handle("POST /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", http.HandlerFunc(h.POSTRPLSourceRoutes))
	http.Handle("DELETE /edev/{id1}/ns/{id2}/addr/{id3}/rpl/{id4}/srt/{id5}", http.HandlerFunc(h.DELETERPLSourceRoutes))
	http.Handle("GET /edev/{id1}/ns/{id2}/ll", http.HandlerFunc(h.GETLLInterfaceList))
	http.Handle("HEAD /edev/{id1}/ns/{id2}/ll", http.HandlerFunc(h.HEADLLInterfaceList))
	http.Handle("PUT /edev/{id1}/ns/{id2}/ll", http.HandlerFunc(h.PUTLLInterfaceList))
	http.Handle("POST /edev/{id1}/ns/{id2}/ll", http.HandlerFunc(h.POSTLLInterfaceList))
	http.Handle("DELETE /edev/{id1}/ns/{id2}/ll", http.HandlerFunc(h.DELETELLInterfaceList))
	http.Handle("GET /edev/{id1}/ns/{id2}/ll/{id3}", http.HandlerFunc(h.GETLLInterface))
	http.Handle("HEAD /edev/{id1}/ns/{id2}/ll/{id3}", http.HandlerFunc(h.HEADLLInterface))
	http.Handle("PUT /edev/{id1}/ns/{id2}/ll/{id3}", http.HandlerFunc(h.PUTLLInterface))
	http.Handle("POST /edev/{id1}/ns/{id2}/ll/{id3}", http.HandlerFunc(h.POSTLLInterface))
	http.Handle("DELETE /edev/{id1}/ns/{id2}/ll/{id3}", http.HandlerFunc(h.DELETELLInterface))
	http.Handle("GET /edev/{id1}/ns/{id2}/ll/{id3}/nbh", http.HandlerFunc(h.GETNeighborList))
	http.Handle("HEAD /edev/{id1}/ns/{id2}/ll/{id3}/nbh", http.HandlerFunc(h.HEADNeighborList))
	http.Handle("PUT /edev/{id1}/ns/{id2}/ll/{id3}/nbh", http.HandlerFunc(h.PUTNeighborList))
	http.Handle("POST /edev/{id1}/ns/{id2}/ll/{id3}/nbh", http.HandlerFunc(h.POSTNeighborList))
	http.Handle("DELETE /edev/{id1}/ns/{id2}/ll/{id3}/nbh", http.HandlerFunc(h.DELETENeighborList))
	http.Handle("GET /edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", http.HandlerFunc(h.GETNeighbor))
	http.Handle("HEAD /edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", http.HandlerFunc(h.HEADNeighbor))
	http.Handle("PUT /edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", http.HandlerFunc(h.PUTNeighbor))
	http.Handle("POST /edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", http.HandlerFunc(h.POSTNeighbor))
	http.Handle("DELETE /edev/{id1}/ns/{id2}/ll/{id3}/nbh/{id4}", http.HandlerFunc(h.DELETENeighbor))
	http.Handle("GET /edev/{id1}/lel", http.HandlerFunc(h.GETLogEventList))
	http.Handle("HEAD /edev/{id1}/lel", http.HandlerFunc(h.HEADLogEventList))
	http.Handle("PUT /edev/{id1}/lel", http.HandlerFunc(h.PUTLogEventList))
	http.Handle("POST /edev/{id1}/lel", http.HandlerFunc(h.POSTLogEventList))
	http.Handle("DELETE /edev/{id1}/lel", http.HandlerFunc(h.DELETELogEventList))
	http.Handle("GET /edev/{id1}/lel/{id2}", http.HandlerFunc(h.GETLogEvent))
	http.Handle("HEAD /edev/{id1}/lel/{id2}", http.HandlerFunc(h.HEADLogEvent))
	http.Handle("PUT /edev/{id1}/lel/{id2}", http.HandlerFunc(h.PUTLogEvent))
	http.Handle("POST /edev/{id1}/lel/{id2}", http.HandlerFunc(h.POSTLogEvent))
	http.Handle("DELETE /edev/{id1}/lel/{id2}", http.HandlerFunc(h.DELETELogEvent))
	http.Handle("GET /edev/{id1}/cfg", http.HandlerFunc(h.GETConfiguration))
	http.Handle("HEAD /edev/{id1}/cfg", http.HandlerFunc(h.HEADConfiguration))
	http.Handle("PUT /edev/{id1}/cfg", http.HandlerFunc(h.PUTConfiguration))
	http.Handle("POST /edev/{id1}/cfg", http.HandlerFunc(h.POSTConfiguration))
	http.Handle("DELETE /edev/{id1}/cfg", http.HandlerFunc(h.DELETEConfiguration))
	http.Handle("GET /edev/{id1}/cfg/prcfg", http.HandlerFunc(h.GETPriceResponseCfgList))
	http.Handle("HEAD /edev/{id1}/cfg/prcfg", http.HandlerFunc(h.HEADPriceResponseCfgList))
	http.Handle("PUT /edev/{id1}/cfg/prcfg", http.HandlerFunc(h.PUTPriceResponseCfgList))
	http.Handle("POST /edev/{id1}/cfg/prcfg", http.HandlerFunc(h.POSTPriceResponseCfgList))
	http.Handle("DELETE /edev/{id1}/cfg/prcfg", http.HandlerFunc(h.DELETEPriceResponseCfgList))
	http.Handle("GET /edev/{id1}/cfg/prcfg/{id2}", http.HandlerFunc(h.GETPriceResponseCfg))
	http.Handle("HEAD /edev/{id1}/cfg/prcfg/{id2}", http.HandlerFunc(h.HEADPriceResponseCfg))
	http.Handle("PUT /edev/{id1}/cfg/prcfg/{id2}", http.HandlerFunc(h.PUTPriceResponseCfg))
	http.Handle("POST /edev/{id1}/cfg/prcfg/{id2}", http.HandlerFunc(h.POSTPriceResponseCfg))
	http.Handle("DELETE /edev/{id1}/cfg/prcfg/{id2}", http.HandlerFunc(h.DELETEPriceResponseCfg))
	http.Handle("GET /edev/{id1}/fs", http.HandlerFunc(h.GETFileStatus))
	http.Handle("HEAD /edev/{id1}/fs", http.HandlerFunc(h.HEADFileStatus))
	http.Handle("PUT /edev/{id1}/fs", http.HandlerFunc(h.PUTFileStatus))
	http.Handle("POST /edev/{id1}/fs", http.HandlerFunc(h.POSTFileStatus))
	http.Handle("DELETE /edev/{id1}/fs", http.HandlerFunc(h.DELETEFileStatus))
	http.Handle("GET /edev/{id1}/lsl", http.HandlerFunc(h.GETLoadShedAvailabilityList))
	http.Handle("HEAD /edev/{id1}/lsl", http.HandlerFunc(h.HEADLoadShedAvailabilityList))
	http.Handle("PUT /edev/{id1}/lsl", http.HandlerFunc(h.PUTLoadShedAvailabilityList))
	http.Handle("POST /edev/{id1}/lsl", http.HandlerFunc(h.POSTLoadShedAvailabilityList))
	http.Handle("DELETE /edev/{id1}/lsl", http.HandlerFunc(h.DELETELoadShedAvailabilityList))
	http.Handle("GET /edev/{id1}/lsl/{id2}", http.HandlerFunc(h.GETLoadShedAvailability))
	http.Handle("HEAD /edev/{id1}/lsl/{id2}", http.HandlerFunc(h.HEADLoadShedAvailability))
	http.Handle("PUT /edev/{id1}/lsl/{id2}", http.HandlerFunc(h.PUTLoadShedAvailability))
	http.Handle("POST /edev/{id1}/lsl/{id2}", http.HandlerFunc(h.POSTLoadShedAvailability))
	http.Handle("DELETE /edev/{id1}/lsl/{id2}", http.HandlerFunc(h.DELETELoadShedAvailability))

	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, os.Interrupt, syscall.SIGTERM)

	go func() {
		log.Printf("Starting EDevice on %s", routes.EDevice)
		err = server.ListenAndServeTLS("./ssl/server.crt", "./ssl/server.key")
		if err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server failed: %v", err)
		}
	}()

	<-sigChan
	log.Println("Shutting down EDevice server...")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := server.Shutdown(ctx); err != nil {
		log.Printf("Server shutdown error: %v", err)
	}
	log.Println("Database connections closed.")
}
