import pandas as pd
import matplotlib.pyplot as plt
import os

# Dissertation Style Settings
plt.rcParams.update({
    "font.family": "serif",
    "font.size": 12,
    "axes.labelsize": 14,
    "legend.fontsize": 10,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "figure.dpi": 300,
    "savefig.bbox": 'tight'
})

def generate_peak_shaving_plot(sim_results_csv, output_path):
    """Generates the main Peak Shaving grid impact plot."""
    if not os.path.exists(sim_results_csv):
        print(f"Error: {sim_results_csv} not found.")
        return

    df = pd.read_csv(sim_results_csv)
    
    # Create the figure
    fig, ax1 = plt.subplots(figsize=(10, 6))
    
    # Plot Voltage on Axis 1
    color_v = 'tab:blue'
    ax1.set_xlabel('Time of Day (Hours)')
    ax1.set_ylabel('Voltage (pu)', color=color_v)
    lns1 = ax1.plot(df['Step']/60.0, df['Avg_Voltage_pu'], color=color_v, label='Average Voltage')
    lns2 = ax1.plot(df['Step']/60.0, df['Min_Voltage_pu'], color='cyan', linestyle='--', label='Minimum Voltage')
    ax1.tick_params(axis='y', labelcolor=color_v)
    ax1.axhline(0.95, color='red', linestyle=':', label='ANSI C84.1 Limit (0.95 pu)')
    
    # Plot Losses on Axis 2
    ax2 = ax1.twinx()
    color_l = 'tab:red'
    ax2.set_ylabel('System Losses (kW)', color=color_l)
    lns3 = ax2.plot(df['Step']/60.0, df['Losses_kW'], color=color_l, label='Line Losses')
    ax2.tick_params(axis='y', labelcolor=color_l)
    
    # Combined Legend
    lns = lns1 + lns2 + lns3
    labs = [l.get_label() for l in lns]
    ax1.legend(lns, labs, loc='upper left')
    
    plt.title('24-Hour Grid Impact of Coordinated DER Participation')
    plt.grid(True, alpha=0.3)
    
    plt.savefig(output_path)
    print(f"✅ Publication-quality plot saved to {output_path}")

def generate_comparison_plot(baseline_csv, coordinated_csv, output_path):
    """Generates a comparison plot between Baseline and EGoT Coordinated response."""
    # Logic to compare two runs...
    pass

if __name__ == "__main__":
    # Define paths
    FIGURES_DIR = "/home/tylor/phd/dissertation/Figures"
    RESULTS_CSV = "egot_results.csv" # Generated by egot_sim.py
    
    # Generate the primary result figure
    generate_peak_shaving_plot(RESULTS_CSV, os.path.join(FIGURES_DIR, "peak_shaving_impact.png"))
