// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/SDevice/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestSdeviceRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerSdeviceRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/sdev_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestSdevicePathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/sdev": nil,
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestSdeviceHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	repo := store.New(":memory:")
	repo.Load()
	h := handler.NewHandler(repo, reg)

	registerSdeviceRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/sdev", true},
		{"GET", "/sdev", true},
		{"HEAD", "/sdev", true},
		{"POST", "/sdev", true},
		{"PUT", "/sdev", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerSdeviceRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /sdev", http.HandlerFunc(h.DELETESelfDevice))
	mux.Handle("GET /sdev", http.HandlerFunc(h.GETSelfDevice))
	mux.Handle("HEAD /sdev", http.HandlerFunc(h.HEADSelfDevice))
	mux.Handle("POST /sdev", http.HandlerFunc(h.POSTSelfDevice))
	mux.Handle("PUT /sdev", http.HandlerFunc(h.PUTSelfDevice))
}
