// Code generated by implement-tests - DO NOT EDIT
package main

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"testing"

	"github.com/Tylores/egot/internal/DR/handler"
	"github.com/Tylores/egot/internal/store"
	"github.com/Tylores/egot/internal/registry"
	"github.com/Tylores/egot/test/routing"
)

func TestDrRouteRegistration(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerDrRoutes(mux, h)

	routeData, err := ioutil.ReadFile("../../test/testdata/dr_routes.json")
	if err != nil {
		t.Skip("Test data not available")
	}

	var testData struct {
		Routes []struct {
			Method string
			Path   string
		}
	}

	if err := json.Unmarshal(routeData, &testData); err != nil {
		t.Fatalf("Failed to parse test data: %v", err)
	}

	expectations := make([]routing.RouteExpectation, 0, len(testData.Routes))
	for _, r := range testData.Routes {
		expectations = append(expectations, routing.RouteExpectation{
			Method: r.Method,
			Path:   r.Path,
		})
	}

	helper := routing.NewTestHelper(mux)
	helper.RegisterExpectedRoutes(expectations)
	all, missing := helper.AssertAllRoutesExist(expectations)
	if !all {
		t.Errorf("Missing %d routes:", len(missing))
		for _, route := range missing {
			t.Errorf("  - %s", route)
		}
	}
}

func TestDrPathParameters(t *testing.T) {
	validator := routing.NewPathParameterValidator()

	patterns := map[string][]string{
		"/dr": nil,
		"/dr/{id1}": {"id1"},
		"/dr/{id1}/actedc": {"id1"},
		"/dr/{id1}/edc": {"id1"},
		"/dr/{id1}/edc/{id2}": {"id1", "id2"},
	}

	for path, expectedParams := range patterns {
		if expectedParams != nil {
			validator.AddPathPattern(path, expectedParams)
		}
		extracted := validator.ExtractParameterNames(path)
		if len(extracted) != len(expectedParams) {
			t.Errorf("Path %s: expected %d params, got %d", path, len(expectedParams), len(extracted))
			continue
		}
	}
}

func TestDrHTTPMethods(t *testing.T) {
	mux := http.NewServeMux()
	reg := registry.New(":memory:")
	reg.Load()
	defer reg.Close()
	repo := store.New(":memory:")
	repo.Load()
	defer repo.Close()
	h := handler.NewHandler(repo, reg)

	registerDrRoutes(mux, h)
	inspector := routing.NewMuxInspector(mux)

	tests := []struct {
		method string
		path   string
		expect bool
	}{
		{"DELETE", "/dr", true},
		{"DELETE", "/dr/{id1}", true},
		{"DELETE", "/dr/{id1}/actedc", true},
		{"DELETE", "/dr/{id1}/edc", true},
		{"DELETE", "/dr/{id1}/edc/{id2}", true},
		{"GET", "/dr", true},
		{"GET", "/dr/{id1}", true},
		{"GET", "/dr/{id1}/actedc", true},
		{"GET", "/dr/{id1}/edc", true},
		{"GET", "/dr/{id1}/edc/{id2}", true},
		{"HEAD", "/dr", true},
		{"HEAD", "/dr/{id1}", true},
		{"HEAD", "/dr/{id1}/actedc", true},
		{"HEAD", "/dr/{id1}/edc", true},
		{"HEAD", "/dr/{id1}/edc/{id2}", true},
		{"POST", "/dr", true},
		{"POST", "/dr/{id1}", true},
		{"POST", "/dr/{id1}/actedc", true},
		{"POST", "/dr/{id1}/edc", true},
		{"POST", "/dr/{id1}/edc/{id2}", true},
		{"PUT", "/dr", true},
		{"PUT", "/dr/{id1}", true},
		{"PUT", "/dr/{id1}/actedc", true},
		{"PUT", "/dr/{id1}/edc", true},
		{"PUT", "/dr/{id1}/edc/{id2}", true},
	}

	for _, test := range tests {
		status, _ := inspector.TestRequest(test.method, test.path)
		found := status != http.StatusNotFound
		if found != test.expect {
			t.Errorf("%s %s: expected found=%v, got %v", test.method, test.path, test.expect, found)
		}
	}
}

func registerDrRoutes(mux *http.ServeMux, h *handler.Handler) {
	mux.Handle("DELETE /dr", http.HandlerFunc(h.DELETEDemandResponseProgramList))
	mux.Handle("DELETE /dr/{id1}", http.HandlerFunc(h.DELETEDemandResponseProgram))
	mux.Handle("DELETE /dr/{id1}/actedc", http.HandlerFunc(h.DELETEActiveEndDeviceControlList))
	mux.Handle("DELETE /dr/{id1}/edc", http.HandlerFunc(h.DELETEEndDeviceControlList))
	mux.Handle("DELETE /dr/{id1}/edc/{id2}", http.HandlerFunc(h.DELETEEndDeviceControl))
	mux.Handle("GET /dr", http.HandlerFunc(h.GETDemandResponseProgramList))
	mux.Handle("GET /dr/{id1}", http.HandlerFunc(h.GETDemandResponseProgram))
	mux.Handle("GET /dr/{id1}/actedc", http.HandlerFunc(h.GETActiveEndDeviceControlList))
	mux.Handle("GET /dr/{id1}/edc", http.HandlerFunc(h.GETEndDeviceControlList))
	mux.Handle("GET /dr/{id1}/edc/{id2}", http.HandlerFunc(h.GETEndDeviceControl))
	mux.Handle("HEAD /dr", http.HandlerFunc(h.HEADDemandResponseProgramList))
	mux.Handle("HEAD /dr/{id1}", http.HandlerFunc(h.HEADDemandResponseProgram))
	mux.Handle("HEAD /dr/{id1}/actedc", http.HandlerFunc(h.HEADActiveEndDeviceControlList))
	mux.Handle("HEAD /dr/{id1}/edc", http.HandlerFunc(h.HEADEndDeviceControlList))
	mux.Handle("HEAD /dr/{id1}/edc/{id2}", http.HandlerFunc(h.HEADEndDeviceControl))
	mux.Handle("POST /dr", http.HandlerFunc(h.POSTDemandResponseProgramList))
	mux.Handle("POST /dr/{id1}", http.HandlerFunc(h.POSTDemandResponseProgram))
	mux.Handle("POST /dr/{id1}/actedc", http.HandlerFunc(h.POSTActiveEndDeviceControlList))
	mux.Handle("POST /dr/{id1}/edc", http.HandlerFunc(h.POSTEndDeviceControlList))
	mux.Handle("POST /dr/{id1}/edc/{id2}", http.HandlerFunc(h.POSTEndDeviceControl))
	mux.Handle("PUT /dr", http.HandlerFunc(h.PUTDemandResponseProgramList))
	mux.Handle("PUT /dr/{id1}", http.HandlerFunc(h.PUTDemandResponseProgram))
	mux.Handle("PUT /dr/{id1}/actedc", http.HandlerFunc(h.PUTActiveEndDeviceControlList))
	mux.Handle("PUT /dr/{id1}/edc", http.HandlerFunc(h.PUTEndDeviceControlList))
	mux.Handle("PUT /dr/{id1}/edc/{id2}", http.HandlerFunc(h.PUTEndDeviceControl))
}
