#!/bin/bash
# Generate route registration tests for all 23 microservices

set -e

TESTDATA_DIR="test/testdata"
CMD_DIR="cmd"

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "Generating route registration test files for all services..."
echo ""

# Function to generate a test file for a service
generate_test_file() {
    local service=$1
    local json_file=$2
    local output_file="${CMD_DIR}/${service}/${service,,}_route_registration_test.go"

    # Skip if JSON doesn't exist
    if [ ! -f "$json_file" ]; then
        echo -e "${BLUE}⊘${NC} $service: No test data (skipping)"
        return
    fi

    # Extract route count from JSON
    local route_count=$(grep -o '"total_routes": [0-9]*' "$json_file" | grep -o '[0-9]*')
    
    if [ -z "$route_count" ] || [ "$route_count" -eq 0 ]; then
        echo -e "${BLUE}⊘${NC} $service: No routes in testdata (skipping)"
        return
    fi

    # Create output directory if needed
    mkdir -p "$(dirname "$output_file")"

    # Write the test file
    cat > "$output_file" << TESTEOF
// Code generated by generate_all_service_tests.sh; DO NOT EDIT.
package main

import (
"net/http"
"testing"

"github.com/Tylores/egot/test/routing"
)

// Test${service}RouteRegistration verifies all ${service} routes are correctly registered.
func Test${service}RouteRegistration(t *testing.T) {
// TODO: Implement route registration
// 1. Create test mux with ${service} routes
// 2. Load expectations from test/testdata/${service,,}_routes.json
// 3. Verify routes are registered
// 4. Check route count matches

// Expected routes: $route_count from WADL
t.Logf("Need to implement ${service} route registration test")
t.Skip("Test not yet implemented - Phase 3 task")
}

// Test${service}PathParameters verifies path parameter extraction.
func Test${service}PathParameters(t *testing.T) {
// TODO: Extract path parameters from routes
// Example: /bill/{id1}/ca/{id2} -> ["id1", "id2"]

validator := routing.NewPathParameterValidator()

// Add path patterns with expected parameters
// validator.AddPathPattern("/path/{id1}", []string{"id1"})

t.Logf("Need to implement ${service} path parameter validation")
t.Skip("Test not yet implemented - Phase 3 task")
}

// Test${service}HTTPMethods verifies HTTP method support.
func Test${service}HTTPMethods(t *testing.T) {
// TODO: Verify all HTTP methods are supported
// Test: GET, POST, PUT, DELETE, HEAD

mux := http.NewServeMux()
// TODO: Register ${service} routes

inspector := routing.NewMuxInspector(mux)

// TODO: Test expected methods
// inspector.AssertRouteMatchesMethod("GET", "/path")

t.Logf("Need to implement ${service} HTTP method verification")
t.Skip("Test not yet implemented - Phase 3 task")
}
TESTEOF

    echo -e "${GREEN}✓${NC} $service: $route_count routes -> $output_file"
}

# Get list of services from existing cmd directories
total_generated=0
while IFS= read -r dir; do
    if [ -d "$dir" ]; then
        service=$(basename "$dir")
        json_file="${TESTDATA_DIR}/${service,,}_routes.json"
        
        # Handle special naming conventions
        case "${service}" in
            Bill) json_file="${TESTDATA_DIR}/bill_routes.json" ;;
            BRS) json_file="${TESTDATA_DIR}/brs_routes.json" ;;
            DCAP) json_file="${TESTDATA_DIR}/dcap_routes.json" ;;
            DERP) json_file="${TESTDATA_DIR}/derp_routes.json" ;;
            DR) json_file="${TESTDATA_DIR}/dr_routes.json" ;;
            EDevice) json_file="${TESTDATA_DIR}/edev_routes.json" ;;
            File) json_file="${TESTDATA_DIR}/file_routes.json" ;;
            MUP) json_file="${TESTDATA_DIR}/mup_routes.json" ;;
            Messaging) json_file="${TESTDATA_DIR}/msg_routes.json" ;;
            Notify) json_file="${TESTDATA_DIR}/ntfy_routes.json" ;;
            PPY) json_file="${TESTDATA_DIR}/ppy_routes.json" ;;
            SDevice) json_file="${TESTDATA_DIR}/sdev_routes.json" ;;
            TariffProfile) json_file="${TESTDATA_DIR}/tp_routes.json" ;;
            TimeOfUse) json_file="${TESTDATA_DIR}/tm_routes.json" ;;
            UPT) json_file="${TESTDATA_DIR}/upt_routes.json" ;;
        esac
        
        if [ -f "$json_file" ]; then
            generate_test_file "$service" "$json_file"
            ((total_generated++)) || true
        fi
    fi
done < <(find "${CMD_DIR}" -maxdepth 1 -type d | sort | tail -n +2)

echo ""
echo -e "${GREEN}✅ Generated test files for ${total_generated} service(s)${NC}"
echo ""
echo "Next steps:"
echo "  1. Review generated test files in cmd/<Service>/*_route_registration_test.go"
echo "  2. Implement test logic by loading expectations from test/testdata/"
echo "  3. Run tests: go test ./cmd/..."
