package main

import (
"encoding/json"
"flag"
"fmt"
"io/ioutil"
"os"
"path/filepath"
"strings"
"text/template"
)

type RouteTestData struct {
ServiceName string `json:"service_name"`
WADLFile    string `json:"wadl_file"`
TotalRoutes int    `json:"total_routes"`
UniquePaths int    `json:"unique_paths"`
Routes      []struct {
Method string `json:"Method"`
Path   string `json:"Path"`
} `json:"routes"`
}

const testTemplate = `// Code generated by generate_route_tests.go; DO NOT EDIT.
package main

import (
"net/http"
"testing"

"github.com/Tylores/egot/test/routing"
)

// Test{{.ServiceName}}RouteRegistration verifies all {{.ServiceName}} routes are correctly registered.
func Test{{.ServiceName}}RouteRegistration(t *testing.T) {
// Create a test mux (copy production routes)
mux := http.NewServeMux()
repo := memory.NewRepository()
handler := NewHandler(repo)
register{{.ServiceName}}Routes(mux, handler)

// Define expected routes from {{.WADLFile}}
expectations := []routing.RouteExpectation{
{{- range .Routes }}
{Method: "{{.Method}}", Path: "{{.Path}}"},
{{- end }}
}

// Verify route registration
helper := routing.NewTestHelper(mux)
helper.RegisterExpectedRoutes(expectations)

// Assert all routes exist
all, missing := helper.AssertAllRoutesExist(expectations)
if !all {
t.Errorf("Missing %d routes:", len(missing))
for _, route := range missing {
t.Errorf("  - %s", route)
}
}

// Assert route count matches
matches, registered, expected := helper.AssertRouteCount(expectations)
if !matches {
t.Errorf("Route count mismatch: expected %d, got %d", expected, registered)
}

// Assert no duplicate routes
validator := routing.NewRouteValidator(mux)
validator.RegisterRoute("", "") // Initialize
if validator.HasDuplicates() {
t.Error("Found duplicate routes")
}
}

// Test{{.ServiceName}}HTTPMethods verifies HTTP method support.
func Test{{.ServiceName}}HTTPMethods(t *testing.T) {
mux := http.NewServeMux()
repo := memory.NewRepository()
handler := NewHandler(repo)
register{{.ServiceName}}Routes(mux, handler)

inspector := routing.NewMuxInspector(mux)

tests := []struct {
method string
path   string
expect bool
}{
{{- range .Routes | uniq }}
{"{{.Method}}", "{{.Path}}", true},
{{- end }}
}

for _, test := range tests {
matched := inspector.AssertRouteMatchesMethod(test.method, test.path)
if matched != test.expect {
t.Errorf("%s %s: expected %v, got %v", test.method, test.path, test.expect, matched)
}
}
}

// Test{{.ServiceName}}PathParameters verifies path parameter extraction.
func Test{{.ServiceName}}PathParameters(t *testing.T) {
validator := routing.NewPathParameterValidator()

{{- $serviceLower := toLower .ServiceName }}
{{- range .Routes }}
{{- if contains .Path "{" }}
validator.AddPathPattern("{{.Path}}", []string{
{{- with extractParams .Path }}
{{- range . }}
"{{.}}",
{{- end }}
{{- end }}
})
{{- end }}
{{- end }}

// Verify parameters are correctly extracted
paramTests := []struct {
path   string
expect []string
}{
{{- range .Routes }}
{{- if contains .Path "{" }}
{
path:   "{{.Path}}",
expect: []string{
{{- with extractParams .Path }}
{{- range . }}
"{{.}}",
{{- end }}
{{- end }}
},
},
{{- end }}
{{- end }}
}

for _, test := range paramTests {
valid, _ := validator.VerifyPathPattern(test.path)
if !valid {
t.Errorf("Path parameters invalid for %s", test.path)
}
}
}
`

func main() {
serviceFlag := flag.String("service", "", "Service name (e.g., Bill). Empty means all.")
flag.Parse()

testDataDir := "./test/testdata"
outputDir := "./cmd"

var services []string
if *serviceFlag != "" {
services = []string{*serviceFlag}
} else {
// Get all test data files
files, err := ioutil.ReadDir(testDataDir)
if err != nil {
fmt.Fprintf(os.Stderr, "Error reading testdata directory: %v\n", err)
os.Exit(1)
}

for _, file := range files {
if strings.HasSuffix(file.Name(), "_routes.json") && !strings.HasPrefix(file.Name(), "device-manager") {
serviceName := strings.TrimSuffix(file.Name(), "_routes.json")
// Capitalize service name
parts := strings.Split(serviceName, "-")
for i, part := range parts {
parts[i] = strings.ToUpper(part[:1]) + part[1:]
}
serviceName = strings.Join(parts, "")
services = append(services, serviceName)
}
}
}

fmt.Printf("Generating test files for %d service(s)...\n", len(services))

for _, service := range services {
// Load route test data
fileName := filepath.Join(testDataDir, strings.ToLower(service)+"_routes.json")

// Handle special cases
if service == "Edev" {
fileName = filepath.Join(testDataDir, "edev_routes.json")
} else if service == "Ntfy" {
fileName = filepath.Join(testDataDir, "ntfy_routes.json")
} else if service == "Msg" {
fileName = filepath.Join(testDataDir, "msg_routes.json")
} else if service == "Ppy" {
fileName = filepath.Join(testDataDir, "ppy_routes.json")
} else if service == "Brs" {
fileName = filepath.Join(testDataDir, "brs_routes.json")
} else if service == "Tm" {
fileName = filepath.Join(testDataDir, "tm_routes.json")
} else if service == "Tp" {
fileName = filepath.Join(testDataDir, "tp_routes.json")
}

data, err := ioutil.ReadFile(fileName)
if err != nil {
fmt.Fprintf(os.Stderr, "Warning: Could not read %s: %v\n", fileName, err)
continue
}

var testData RouteTestData
err = json.Unmarshal(data, &testData)
if err != nil {
fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", fileName, err)
continue
}

// Skip if no routes
if len(testData.Routes) == 0 {
fmt.Printf("⊘ %s: No routes found\n", service)
continue
}

// For now, just print info
fmt.Printf("✓ %s: %d routes (%d paths)\n", 
service, testData.TotalRoutes, testData.UniquePaths)
}

fmt.Printf("\n✅ Reviewed %d service(s)\n", len(services))
fmt.Printf("\nNote: To generate test files, use the template above.\n")
}
